package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserProfiles<M extends BaseUserProfiles<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}
	
	public void setOpenimageatonce(java.lang.String openimageatonce) {
		set("openimageatonce", openimageatonce);
	}
	
	public java.lang.String getOpenimageatonce() {
		return getStr("openimageatonce");
	}
	
	public void setSignfilepath(java.lang.String signfilepath) {
		set("signfilepath", signfilepath);
	}
	
	public java.lang.String getSignfilepath() {
		return getStr("signfilepath");
	}
	
	public void setEnableesign(java.lang.String enableesign) {
		set("enableesign", enableesign);
	}
	
	public java.lang.String getEnableesign() {
		return getStr("enableesign");
	}
	
	public void setRegThirdPanelCollapsed(java.lang.String regThirdPanelCollapsed) {
		set("reg_third_panel_collapsed", regThirdPanelCollapsed);
	}
	
	public java.lang.String getRegThirdPanelCollapsed() {
		return getStr("reg_third_panel_collapsed");
	}
	
	public void setRegSamenamePanelCollapsed(java.lang.String regSamenamePanelCollapsed) {
		set("reg_samename_panel_collapsed", regSamenamePanelCollapsed);
	}
	
	public java.lang.String getRegSamenamePanelCollapsed() {
		return getStr("reg_samename_panel_collapsed");
	}
	
	public void setBeforeSaveScan(java.lang.String beforeSaveScan) {
		set("before_save_scan", beforeSaveScan);
	}
	
	public java.lang.String getBeforeSaveScan() {
		return getStr("before_save_scan");
	}
	
	public void setAfterSavePrint(java.lang.String afterSavePrint) {
		set("after_save_print", afterSavePrint);
	}
	
	public java.lang.String getAfterSavePrint() {
		return getStr("after_save_print");
	}
	
	public void setStudyformPrintCopies(java.lang.Integer studyformPrintCopies) {
		set("studyform_print_copies", studyformPrintCopies);
	}
	
	public java.lang.Integer getStudyformPrintCopies() {
		return getInt("studyform_print_copies");
	}
	
	public void setSchformPrintCopies(java.lang.Integer schformPrintCopies) {
		set("schform_print_copies", schformPrintCopies);
	}
	
	public java.lang.Integer getSchformPrintCopies() {
		return getInt("schform_print_copies");
	}
	
	public void setMyreportCollapsed(java.lang.String myreportCollapsed) {
		set("myreport_collapsed", myreportCollapsed);
	}
	
	public java.lang.String getMyreportCollapsed() {
		return getStr("myreport_collapsed");
	}
	
	public void setMyfilterCollapsed(java.lang.String myfilterCollapsed) {
		set("myfilter_collapsed", myfilterCollapsed);
	}
	
	public java.lang.String getMyfilterCollapsed() {
		return getStr("myfilter_collapsed");
	}
	
	public void setReportAssistantCollapsed(java.lang.String reportAssistantCollapsed) {
		set("report_assistant_collapsed", reportAssistantCollapsed);
	}
	
	public java.lang.String getReportAssistantCollapsed() {
		return getStr("report_assistant_collapsed");
	}
	
	public void setWorklistRefreshInterval(java.lang.Integer worklistRefreshInterval) {
		set("worklist_refresh_interval", worklistRefreshInterval);
	}
	
	public java.lang.Integer getWorklistRefreshInterval() {
		return getInt("worklist_refresh_interval");
	}
	
	public void setPosOrNeg(java.lang.String posOrNeg) {
		set("pos_or_neg", posOrNeg);
	}
	
	public java.lang.String getPosOrNeg() {
		return getStr("pos_or_neg");
	}
	
	public void setDatagridWorklistDg(java.lang.String datagridWorklistDg) {
		set("datagrid_worklist_dg", datagridWorklistDg);
	}
	
	public java.lang.String getDatagridWorklistDg() {
		return getStr("datagrid_worklist_dg");
	}
	
	public void setDatagridRegisterDg1Reg(java.lang.String datagridRegisterDg1Reg) {
		set("datagrid_register_dg1_reg", datagridRegisterDg1Reg);
	}
	
	public java.lang.String getDatagridRegisterDg1Reg() {
		return getStr("datagrid_register_dg1_reg");
	}
	
	public void setDatagridScheduleDgSearchSch(java.lang.String datagridScheduleDgSearchSch) {
		set("datagrid_schedule_dg_search_sch", datagridScheduleDgSearchSch);
	}
	
	public java.lang.String getDatagridScheduleDgSearchSch() {
		return getStr("datagrid_schedule_dg_search_sch");
	}
	
	public void setDatagridExamineSearchdgExam(java.lang.String datagridExamineSearchdgExam) {
		set("datagrid_examine_searchdg_exam", datagridExamineSearchdgExam);
	}
	
	public java.lang.String getDatagridExamineSearchdgExam() {
		return getStr("datagrid_examine_searchdg_exam");
	}
	
	public void setPaginationWorklistDg(java.lang.String paginationWorklistDg) {
		set("pagination_worklist_dg", paginationWorklistDg);
	}
	
	public java.lang.String getPaginationWorklistDg() {
		return getStr("pagination_worklist_dg");
	}
	
	public void setPaginationRegisterDg1Reg(java.lang.String paginationRegisterDg1Reg) {
		set("pagination_register_dg1_reg", paginationRegisterDg1Reg);
	}
	
	public java.lang.String getPaginationRegisterDg1Reg() {
		return getStr("pagination_register_dg1_reg");
	}
	
	public void setPaginationScheduleDgSearchSch(java.lang.String paginationScheduleDgSearchSch) {
		set("pagination_schedule_dg_search_sch", paginationScheduleDgSearchSch);
	}
	
	public java.lang.String getPaginationScheduleDgSearchSch() {
		return getStr("pagination_schedule_dg_search_sch");
	}
	
	public void setPaginationExamineSearchdgExam(java.lang.String paginationExamineSearchdgExam) {
		set("pagination_examine_searchdg_exam", paginationExamineSearchdgExam);
	}
	
	public java.lang.String getPaginationExamineSearchdgExam() {
		return getStr("pagination_examine_searchdg_exam");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.util.Date getModifytime() {
		return get("modifytime");
	}
	
	public void setDicModality(java.lang.String dicModality) {
		set("dicModality", dicModality);
	}
	
	public java.lang.String getDicModality() {
		return getStr("dicModality");
	}
	
	public void setDefaultDicModality(java.lang.String defaultDicModality) {
		set("defaultDicModality", defaultDicModality);
	}
	
	public java.lang.String getDefaultDicModality() {
		return getStr("defaultDicModality");
	}
	
	public void setTheme(java.lang.String theme) {
		set("theme", theme);
	}
	
	public java.lang.String getTheme() {
		return getStr("theme");
	}
	public void setAutoSaveReportInterval(java.lang.String auto_save_report_interval) {
		set("auto_save_report_interval", auto_save_report_interval);
	}
	
	public java.lang.String getAutoSaveReportInterval() {
		return get("auto_save_report_interval");
	}
	
	public void setReportHistoryreportCollapsed(java.lang.String reportHistoryreportCollapsed) {
		set("report_historyreport_collapsed", reportHistoryreportCollapsed);
	}
	
	public java.lang.String getReportHistoryreportCollapsed() {
		return getStr("report_historyreport_collapsed");
	}
	
	public void setReportDescFontsize(java.lang.String reportDescFontsize) {
		set("report_desc_fontsize", reportDescFontsize);
	}
	
	public java.lang.String getReportDescFontsize() {
		return getStr("report_desc_fontsize");
	}
	
	public void setReportResultFontsize(java.lang.String reportResultFontsize) {
		set("report_result_fontsize", reportResultFontsize);
	}
	
	public java.lang.String getReportResultFontsize() {
		return getStr("report_result_fontsize");
	}
	
	public void setReportEditorColor(java.lang.String reportEditorColor) {
		set("report_editor_color", reportEditorColor);
	}
	
	public java.lang.String getReportEditorColor() {
		return getStr("report_editor_color");
	}
	public void setReportAudit(java.lang.String report_audit) {
		set("report_audit", report_audit);
	}
	
	public java.lang.String getReportAudit() {
		return get("report_audit");
	}
	
	public void setReportSubmit(java.lang.String report_submit) {
		set("report_submit", report_submit);
	}
	
	public java.lang.String getReportSubmit() {
		return get("report_submit");
	}
}
