package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudyAcquisitionModeDefault<M extends BaseStudyAcquisitionModeDefault<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setExamPollution(java.lang.String exam_pollution) {
		set("exam_pollution", exam_pollution);
	}
	
	public java.lang.String getExamPollution() {
		return getStr("exam_pollution");
	}
	
	public void setDelayedAcquisition(java.lang.Integer delayedAcquisition) {
		set("delayed_acquisition", delayedAcquisition);
	}
	
	public java.lang.Integer getDelayedAcquisition() {
		return getInt("delayed_acquisition");
	}
	
	public void setDelayedAcquisition1(java.lang.Integer delayedAcquisition1) {
		set("delayed_acquisition1", delayedAcquisition1);
	}
	
	public java.lang.Integer getDelayedAcquisition1() {
		return getInt("delayed_acquisition1");
	}
	
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}
	
	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
}
