package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMwlitem<M extends BaseMwlitem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setPatientidfk(java.lang.Integer patientidfk) {
		set("patientidfk", patientidfk);
	}
	
	public java.lang.Integer getPatientidfk() {
		return getInt("patientidfk");
	}
	
	public void setAdmissionidfk(java.lang.Integer admissionidfk) {
		set("admissionidfk", admissionidfk);
	}
	
	public java.lang.Integer getAdmissionidfk() {
		return getInt("admissionidfk");
	}
	
	public void setStudyorderidfk(java.lang.Integer studyorderidfk) {
		set("studyorderidfk", studyorderidfk);
	}
	
	public java.lang.Integer getStudyorderidfk() {
		return getInt("studyorderidfk");
	}
	
	public void setStudyIuid(java.lang.String studyIuid) {
		set("study_iuid", studyIuid);
	}
	
	public java.lang.String getStudyIuid() {
		return getStr("study_iuid");
	}
	
	public void setAdmissionId(java.lang.String admissionId) {
		set("admission_id", admissionId);
	}
	
	public java.lang.String getAdmissionId() {
		return getStr("admission_id");
	}
	
	public void setAccessionNo(java.lang.String accessionNo) {
		set("accession_no", accessionNo);
	}
	
	public java.lang.String getAccessionNo() {
		return getStr("accession_no");
	}
	
	public void setSpsStatus(java.lang.Integer spsStatus) {
		set("sps_status", spsStatus);
	}
	
	public java.lang.Integer getSpsStatus() {
		return getInt("sps_status");
	}
	
	public void setSpsId(java.lang.String spsId) {
		set("sps_id", spsId);
	}
	
	public java.lang.String getSpsId() {
		return getStr("sps_id");
	}
	
	public void setStartDatetime(java.util.Date startDatetime) {
		set("start_datetime", startDatetime);
	}
	
	public java.util.Date getStartDatetime() {
		return get("start_datetime");
	}
	
	public void setStationAet(java.lang.String stationAet) {
		set("station_aet", stationAet);
	}
	
	public java.lang.String getStationAet() {
		return getStr("station_aet");
	}
	
	public void setStationName(java.lang.String stationName) {
		set("station_name", stationName);
	}
	
	public java.lang.String getStationName() {
		return getStr("station_name");
	}
	
	public void setModality(java.lang.String modality) {
		set("modality", modality);
	}
	
	public java.lang.String getModality() {
		return getStr("modality");
	}
	
	public void setIssuerPatientid(java.lang.String issuerPatientid) {
		set("issuer_patientid", issuerPatientid);
	}
	
	public java.lang.String getIssuerPatientid() {
		return getStr("issuer_patientid");
	}
	
	public void setReqPhysician(java.lang.String reqPhysician) {
		set("req_physician", reqPhysician);
	}
	
	public java.lang.String getReqPhysician() {
		return getStr("req_physician");
	}
	
	public void setRefePhysician(java.lang.String refePhysician) {
		set("refe_physician", refePhysician);
	}
	
	public java.lang.String getRefePhysician() {
		return getStr("refe_physician");
	}
	
	public void setPerfPhysician(java.lang.String perfPhysician) {
		set("perf_physician", perfPhysician);
	}
	
	public java.lang.String getPerfPhysician() {
		return getStr("perf_physician");
	}
	
	public void setReqProcId(java.lang.String reqProcId) {
		set("req_proc_id", reqProcId);
	}
	
	public java.lang.String getReqProcId() {
		return getStr("req_proc_id");
	}
	
	public void setReqProcDesc(java.lang.String reqProcDesc) {
		set("req_proc_desc", reqProcDesc);
	}
	
	public java.lang.String getReqProcDesc() {
		return getStr("req_proc_desc");
	}
	
	public void setSpsDesc(java.lang.String spsDesc) {
		set("sps_desc", spsDesc);
	}
	
	public java.lang.String getSpsDesc() {
		return getStr("sps_desc");
	}
	
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	public java.util.Date getUpdatedTime() {
		return get("updated_time");
	}
	
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	public java.util.Date getCreatedTime() {
		return get("created_time");
	}
	
	public void setCharacter(java.lang.String character) {
		set("character", character);
	}
	
	public java.lang.String getCharacter() {
		return getStr("character");
	}
	
	public void setSpsDescPinyin(java.lang.String spsDescPinyin) {
		set("sps_desc_pinyin", spsDescPinyin);
	}
	
	public java.lang.String getSpsDescPinyin() {
		return getStr("sps_desc_pinyin");
	}
	
}
