package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicExamEquip<M extends BaseDicExamEquip<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setExamId(java.lang.Integer examId) {
		set("exam_id", examId);
	}
	
	public java.lang.Integer getExamId() {
		return getInt("exam_id");
	}

	public void setEquipId(java.lang.Integer equipId) {
		set("equip_id", equipId);
	}
	
	public java.lang.Integer getEquipId() {
		return getInt("equip_id");
	}

}
