package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudyorder<M extends BaseStudyorder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setPatientidfk(java.lang.Integer patientidfk) {
		set("patientidfk", patientidfk);
	}
	
	public java.lang.Integer getPatientidfk() {
		return getInt("patientidfk");
	}
	
	public void setAdmissionidfk(java.lang.Integer admissionidfk) {
		set("admissionidfk", admissionidfk);
	}
	
	public java.lang.Integer getAdmissionidfk() {
		return getInt("admissionidfk");
	}
	
	public void setPatientid(java.lang.String patientid) {
		set("patientid", patientid);
	}
	
	public java.lang.String getPatientid() {
		return getStr("patientid");
	}
	
	public void setStudyid(java.lang.String studyid) {
		set("studyid", studyid);
	}
	
	public java.lang.String getStudyid() {
		return getStr("studyid");
	}
	
	public void setSequencenumber(java.lang.String sequencenumber) {
		set("sequencenumber", sequencenumber);
	}
	
	public java.lang.String getSequencenumber() {
		return getStr("sequencenumber");
	}
	
	public void setAccessionnumber(java.lang.String accessionnumber) {
		set("accessionnumber", accessionnumber);
	}
	
	public java.lang.String getAccessionnumber() {
		return getStr("accessionnumber");
	}
	
	public void setStudyinstanceuid(java.lang.String studyinstanceuid) {
		set("studyinstanceuid", studyinstanceuid);
	}
	
	public java.lang.String getStudyinstanceuid() {
		return getStr("studyinstanceuid");
	}
	
	public void setStudydescription(java.lang.String studydescription) {
		set("studydescription", studydescription);
	}
	
	public java.lang.String getStudydescription() {
		return getStr("studydescription");
	}
	
	public void setStudyitems(java.lang.String studyitems) {
		set("studyitems", studyitems);
	}
	
	public java.lang.String getStudyitems() {
		return getStr("studyitems");
	}
	
	public void setAppdatetime(java.util.Date appdatetime) {
		set("appdatetime", appdatetime);
	}
	
	public java.util.Date getAppdatetime() {
		return get("appdatetime");
	}
	
	public void setAppointmenttime(java.util.Date appointmenttime) {
		set("appointmenttime", appointmenttime);
	}
	
	public java.util.Date getAppointmenttime() {
		return get("appointmenttime");
	}
	
	public void setAppdeptcode(java.lang.String appdeptcode) {
		set("appdeptcode", appdeptcode);
	}
	
	public java.lang.String getAppdeptcode() {
		return getStr("appdeptcode");
	}
	
	public void setAppdeptname(java.lang.String appdeptname) {
		set("appdeptname", appdeptname);
	}
	
	public java.lang.String getAppdeptname() {
		return getStr("appdeptname");
	}
	
	public void setAppdoctorcode(java.lang.String appdoctorcode) {
		set("appdoctorcode", appdoctorcode);
	}
	
	public java.lang.String getAppdoctorcode() {
		return getStr("appdoctorcode");
	}
	
	public void setAppdoctorname(java.lang.String appdoctorname) {
		set("appdoctorname", appdoctorname);
	}
	
	public java.lang.String getAppdoctorname() {
		return getStr("appdoctorname");
	}
	
	public void setPerformeddeptcode(java.lang.String performeddeptcode) {
		set("performeddeptcode", performeddeptcode);
	}
	
	public java.lang.String getPerformeddeptcode() {
		return getStr("performeddeptcode");
	}
	
	public void setPerformeddeptname(java.lang.String performeddeptname) {
		set("performeddeptname", performeddeptname);
	}
	
	public java.lang.String getPerformeddeptname() {
		return getStr("performeddeptname");
	}
	
	public void setPriority(java.lang.String priority) {
		set("priority", priority);
	}
	
	public java.lang.String getPriority() {
		return getStr("priority");
	}
	
	public void setModalityType(java.lang.String modalityType) {
		set("modality_type", modalityType);
	}
	
	public java.lang.String getModalityType() {
		return getStr("modality_type");
	}
	
	public void setModalityid(java.lang.Integer modalityid) {
		set("modalityid", modalityid);
	}
	
	public java.lang.Integer getModalityid() {
		return getInt("modalityid");
	}
	
	public void setOrgan(java.lang.Integer organ) {
		set("organ", organ);
	}
	
	public java.lang.Integer getOrgan() {
		return getInt("organ");
	}
	
	public void setOrganName(java.lang.String organName) {
		set("organ_name", organName);
	}
	
	public java.lang.String getOrganName() {
		return getStr("organ_name");
	}
	
	public void setTriagemodalityid(java.lang.Integer triagemodalityid) {
		set("triagemodalityid", triagemodalityid);
	}
	
	public java.lang.Integer getTriagemodalityid() {
		return getInt("triagemodalityid");
	}
	
	public void setNumberofstudyrelatedinstances(java.lang.Integer numberofstudyrelatedinstances) {
		set("numberofstudyrelatedinstances", numberofstudyrelatedinstances);
	}
	
	public java.lang.Integer getNumberofstudyrelatedinstances() {
		return getInt("numberofstudyrelatedinstances");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setImagestatus(java.lang.Integer imagestatus) {
		set("imagestatus", imagestatus);
	}
	
	public java.lang.Integer getImagestatus() {
		return getInt("imagestatus");
	}
	
	public void setStudydatetime(java.util.Date studydatetime) {
		set("studydatetime", studydatetime);
	}
	
	public java.util.Date getStudydatetime() {
		return get("studydatetime");
	}
	
	public void setStudycompletetime(java.util.Date studycompletetime) {
		set("studycompletetime", studycompletetime);
	}
	
	public java.util.Date getStudycompletetime() {
		return get("studycompletetime");
	}
	
	public void setRegdatetime(java.util.Date regdatetime) {
		set("regdatetime", regdatetime);
	}
	
	public java.util.Date getRegdatetime() {
		return get("regdatetime");
	}
	
	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public void setCreatorname(java.lang.String creatorname) {
		set("creatorname", creatorname);
	}
	
	public java.lang.String getCreatorname() {
		return getStr("creatorname");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.util.Date getModifytime() {
		return get("modifytime");
	}
	
	public void setPri(java.lang.Integer pri) {
		set("pri", pri);
	}
	
	public java.lang.Integer getPri() {
		return getInt("pri");
	}
	
	public void setPrecedence(java.lang.Integer precedence) {
		set("precedence", precedence);
	}
	
	public java.lang.Integer getPrecedence() {
		return getInt("precedence");
	}
	
	public void setReportAssignee(java.lang.Integer reportAssignee) {
		set("report_assignee", reportAssignee);
	}
	
	public java.lang.Integer getReportAssignee() {
		return getInt("report_assignee");
	}
	
	public void setChargeStatus(java.lang.String chargeStatus) {
		set("charge_status", chargeStatus);
	}
	
	public java.lang.String getChargeStatus() {
		return getStr("charge_status");
	}
	
	public void setApphospitalcode(java.lang.String apphospitalcode) {
		set("apphospitalcode", apphospitalcode);
	}
	
	public java.lang.String getApphospitalcode() {
		return getStr("apphospitalcode");
	}
	
	public void setApphospitalname(java.lang.String apphospitalname) {
		set("apphospitalname", apphospitalname);
	}
	
	public java.lang.String getApphospitalname() {
		return getStr("apphospitalname");
	}
	
	public void setExaminationMethod(java.lang.Integer examinationMethod) {
		set("examination_method", examinationMethod);
	}
	
	public java.lang.Integer getExaminationMethod() {
		return getInt("examination_method");
	}

	public void setArrivedtime(java.util.Date arrivedtime) {
		set("arrivedtime", arrivedtime);
	}
	
	public java.util.Date getArrivedtime() {
		return get("arrivedtime");
	}
	
	public void setFilmtakenaway(java.lang.Integer filmtakenaway) {
		set("filmtakenaway", filmtakenaway);
	}
	
	public java.lang.Integer getFilmtakenaway() {
		return getInt("filmtakenaway");
	}
	
	public void setCancelreason(java.lang.String cancelreason) {
		set("cancelreason", cancelreason);
	}
	
	public java.lang.String getCancelreason() {
		return getStr("cancelreason");
	}
	
	public void setEorderfk(java.lang.Integer eorderfk) {
		set("eorderfk", eorderfk);
	}
	
	public java.lang.Integer getEorderfk() {
		return getInt("eorderfk");
	}
	
	public void setEorderid(java.lang.String eorderid) {
		set("eorderid", eorderid);
	}
	
	public java.lang.String getEorderid() {
		return getStr("eorderid");
	}
	
	public void setEorderidIssuer(java.lang.String eorderid_issuer) {
		set("eorderid_issuer", eorderid_issuer);
	}
	
	public java.lang.String getEorderidIssuer() {
		return getStr("eorderid_issuer");
	}
	
	public void setNuclide(java.lang.Integer  nuclide) {
		set("nuclide",  nuclide);
	}
	
	public java.lang.Integer getNuclide() {
		return getInt("nuclide");
	}
	
	public void setTracer(java.lang.Integer tracer) {
		set("tracer", tracer);
	}
	
	public java.lang.Integer getTracer() {
		return getInt("tracer");
	}
	
}
