package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUnmatchstudy<M extends BaseUnmatchstudy<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPatientid(java.lang.String patientid) {
		set("patientid", patientid);
	}
	
	public java.lang.String getPatientid() {
		return getStr("patientid");
	}

	public void setPatientname(java.lang.String patientname) {
		set("patientname", patientname);
	}
	
	public java.lang.String getPatientname() {
		return getStr("patientname");
	}

	public void setBirthdate(java.lang.String birthdate) {
		set("birthdate", birthdate);
	}
	
	public java.lang.String getBirthdate() {
		return getStr("birthdate");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public void setAccessionnumber(java.lang.String accessionnumber) {
		set("accessionnumber", accessionnumber);
	}
	
	public java.lang.String getAccessionnumber() {
		return getStr("accessionnumber");
	}

	public void setStudyid(java.lang.String studyid) {
		set("studyid", studyid);
	}
	
	public java.lang.String getStudyid() {
		return getStr("studyid");
	}

	public void setStudyinstanceuid(java.lang.String studyinstanceuid) {
		set("studyinstanceuid", studyinstanceuid);
	}
	
	public java.lang.String getStudyinstanceuid() {
		return getStr("studyinstanceuid");
	}

	public void setStudydatetime(java.util.Date studydatetime) {
		set("studydatetime", studydatetime);
	}
	
	public java.util.Date getStudydatetime() {
		return get("studydatetime");
	}

	public void setModality(java.lang.String modality) {
		set("modality", modality);
	}
	
	public java.lang.String getModality() {
		return getStr("modality");
	}

	public void setStudydescription(java.lang.String studydescription) {
		set("studydescription", studydescription);
	}
	
	public java.lang.String getStudydescription() {
		return getStr("studydescription");
	}

	public void setNumberofimages(java.lang.Integer numberofimages) {
		set("numberofimages", numberofimages);
	}
	
	public java.lang.Integer getNumberofimages() {
		return getInt("numberofimages");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setMatchflag(java.lang.Integer matchflag) {
		set("matchflag", matchflag);
	}
	
	public java.lang.Integer getMatchflag() {
		return getInt("matchflag");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
