package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLabelfolder<M extends BaseLabelfolder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setFoldername(java.lang.String foldername) {
		set("foldername", foldername);
	}
	
	public java.lang.String getFoldername() {
		return getStr("foldername");
	}

	public void setParent(java.lang.Integer parent) {
		set("parent", parent);
	}
	
	public java.lang.Integer getParent() {
		return getInt("parent");
	}

	public void setIspublic(java.lang.String ispublic) {
		set("ispublic", ispublic);
	}
	
	public java.lang.String getIspublic() {
		return getStr("ispublic");
	}

	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

}
