package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeptReportTaskSetting<M extends BaseDeptReportTaskSetting<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setEnableReportTask(java.lang.String enable_report_task) {
		set("enable_report_task", enable_report_task);
	}
	
	public java.lang.String getEnableReportTask() {
		return getStr("enable_report_task");
	}

	public void setEnableAdard(java.lang.String enableAdard) {
		set("enable_ADARD", enableAdard);
	}
	
	public java.lang.String getEnableAdard() {
		return getStr("enable_ADARD");
	}

	public void setEnableAmefsptsp(java.lang.String enableAmefsptsp) {
		set("enable_AMEFSPTSP", enableAmefsptsp);
	}
	
	public java.lang.String getEnableAmefsptsp() {
		return getStr("enable_AMEFSPTSP");
	}

	public void setEnableEed(java.lang.String enableEed) {
		set("enable_EED", enableEed);
	}
	
	public java.lang.String getEnableEed() {
		return getStr("enable_EED");
	}
	
	public void setEnableEped(java.lang.String enableEped) {
		set("enable_EPED", enableEped);
	}
	
	public java.lang.String getEnableEped() {
		return getStr("enable_EPED");
	}

	public void setEnableSd(java.lang.String enableSd) {
		set("enable_SD", enableSd);
	}
	
	public java.lang.String getEnableSd() {
		return getStr("enable_SD");
	}

	public void setEnableTored(java.lang.String enableTored) {
		set("enable_TORED", enableTored);
	}
	
	public java.lang.String getEnableTored() {
		return getStr("enable_TORED");
	}

	public void setEnableRrred(java.lang.String enableRrred) {
		set("enable_RRRED", enableRrred);
	}
	
	public java.lang.String getEnableRrred() {
		return getStr("enable_RRRED");
	}
	
	public void setEnableAdq(java.lang.String enableAdq) {
		set("enable_ADQ", enableAdq);
	}
	
	public java.lang.String getEnableAdq() {
		return getStr("enable_ADQ");
	}
	
	public void setEnableAdmq(java.lang.String enableAdmq) {
		set("enable_ADMQ", enableAdmq);
	}
	
	public java.lang.String getEnableAdmq() {
		return getStr("enable_ADMQ");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
