package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleModule<M extends BaseRoleModule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setRoleid(java.lang.Integer roleid) {
		set("roleid", roleid);
	}
	
	public java.lang.Integer getRoleid() {
		return getInt("roleid");
	}

	public void setModule(java.lang.String module) {
		set("module", module);
	}
	
	public java.lang.String getModule() {
		return getStr("module");
	}
}
