package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFavoritesreport<M extends BaseFavoritesreport<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setReportDesc(java.lang.String reportDesc) {
		set("report_desc", reportDesc);
	}
	
	public java.lang.String getReportDesc() {
		return getStr("report_desc");
	}

	public void setReportId(java.lang.Integer reportId) {
		set("report_id", reportId);
	}
	
	public java.lang.Integer getReportId() {
		return getInt("report_id");
	}

	public void setFavoritesId(java.lang.Integer favoritesId) {
		set("favorites_id", favoritesId);
	}
	
	public java.lang.Integer getFavoritesId() {
		return getInt("favorites_id");
	}

	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
