package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInjection<M extends BaseInjection<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setStudyorderfk(java.lang.Integer studyorderfk) {
		set("studyorderfk", studyorderfk);
	}
	
	public java.lang.Integer getStudyorderfk() {
		return getInt("studyorderfk");
	}

	public void setStudyid(java.lang.String studyid) {
		set("studyid", studyid);
	}
	
	public java.lang.String getStudyid() {
		return getStr("studyid");
	}

	public void setAdministrationMethod(java.lang.String administrationMethod) {
		set("administration_method", administrationMethod);
	}
	
	public java.lang.String getAdministrationMethod() {
		return getStr("administration_method");
	}

	public void setInjectionSite(java.lang.Integer injectionSite) {
		set("injection_site", injectionSite);
	}
	
	public java.lang.Integer getInjectionSite() {
		return getInt("injection_site");
	}

	public void setInjecterId(java.lang.Integer injecterId) {
		set("injecter_id", injecterId);
	}
	
	public java.lang.Integer getInjecterId() {
		return getInt("injecter_id");
	}

	public void setPollution(java.lang.String pollution) {
		set("pollution", pollution);
	}
	
	public java.lang.String getPollution() {
		return getStr("pollution");
	}

	public void setDrugSource(java.lang.String drugSource) {
		set("drug_source", drugSource);
	}
	
	public java.lang.String getDrugSource() {
		return getStr("drug_source");
	}
	
	public void setPrescription_dose(java.math.BigDecimal prescription_dose) {
		set("prescription_dose", prescription_dose);
	}
	
	public java.math.BigDecimal getPrescription_dose() {
		return get("prescription_dose");
	}

	public void setInjectionDosePre(java.math.BigDecimal injectionDosePre) {
		set("injection_dose_pre", injectionDosePre);
	}
	
	public java.math.BigDecimal getInjectionDosePre() {
		return get("injection_dose_pre");
	}

	public void setInjectionDoseAfter(java.math.BigDecimal injectionDoseAfter) {
		set("injection_dose_after", injectionDoseAfter);
	}
	
	public java.math.BigDecimal getInjectionDoseAfter() {
		return get("injection_dose_after");
	}

	public void setInjectionDoseReal(java.math.BigDecimal injectionDoseReal) {
		set("injection_dose_real", injectionDoseReal);
	}
	
	public java.math.BigDecimal getInjectionDoseReal() {
		return get("injection_dose_real");
	}

	public void setInjectionRemark(java.lang.String injectionRemark) {
		set("injection_remark", injectionRemark);
	}
	
	public java.lang.String getInjectionRemark() {
		return getStr("injection_remark");
	}

	public void setReceptionNurse(java.lang.Integer receptionNurse) {
		set("reception_nurse", receptionNurse);
	}
	
	public java.lang.Integer getReceptionNurse() {
		return getInt("reception_nurse");
	}

	public void setInjectionDatetime(java.util.Date injectionDatetime) {
		set("injection_datetime", injectionDatetime);
	}
	
	public java.util.Date getInjectionDatetime() {
		return get("injection_datetime");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.util.Date getModifytime() {
		return get("modifytime");
	}

	public void setInjecterName(java.lang.String injecter_name) {
		set("injecter_name", injecter_name);
	}
	
	public java.lang.String getInjecterName() {
		return getStr("injecter_name");
	}
	
	public void setReceptionNurseName(java.lang.String reception_nurse_name) {
		set("reception_nurse_name", reception_nurse_name);
	}
	
	public java.lang.String getReceptionNurseName() {
		return getStr("reception_nurse_name");
	}
}
