package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResearchRole<M extends BaseResearchRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setRolename(java.lang.String rolename) {
		set("rolename", rolename);
	}
	
	public java.lang.String getRolename() {
		return getStr("rolename");
	}
	
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
	public void setUserLevel(java.lang.Integer user_level) {
		set("user_level", user_level);
	}
	
	public java.lang.Integer getUserLevel() {
		return getInt("user_level");
	}
	
}
