package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicEmployee<M extends BaseDicEmployee<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setJobnumber(java.lang.String jobnumber) {
		set("jobnumber", jobnumber);
	}
	
	public java.lang.String getJobnumber() {
		return getStr("jobnumber");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setDeptfk(java.lang.Integer deptfk) {
		set("deptfk", deptfk);
	}
	
	public java.lang.Integer getDeptfk() {
		return getInt("deptfk");
	}

	public void setDeptcode(java.lang.String deptcode) {
		set("deptcode", deptcode);
	}
	
	public java.lang.String getDeptcode() {
		return getStr("deptcode");
	}

	public void setDeptname(java.lang.String deptname) {
		set("deptname", deptname);
	}
	
	public java.lang.String getDeptname() {
		return getStr("deptname");
	}

	public void setProfession(java.lang.String profession) {
		set("profession", profession);
	}
	
	public java.lang.String getProfession() {
		return getStr("profession");
	}

	public void setInstitutionid(java.lang.Integer institutionid) {
		set("institutionid", institutionid);
	}
	
	public java.lang.Integer getInstitutionid() {
		return getInt("institutionid");
	}
	
	public void setDeleted(java.lang.String deleted) {
        set("deleted", deleted);
    }

    public java.lang.String getDeleted() {
        return get("deleted");
    }

}
