package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotice<M extends BaseNotice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setContenthtml(java.lang.String contenthtml) {
		set("contenthtml", contenthtml);
	}
	
	public java.lang.String getContenthtml() {
		return getStr("contenthtml");
	}

	public void setContenttxt(java.lang.String contenttxt) {
		set("contenttxt", contenttxt);
	}
	
	public java.lang.String getContenttxt() {
		return getStr("contenttxt");
	}

	public void setReleasedflag(java.lang.Integer releasedflag) {
		set("releasedflag", releasedflag);
	}
	
	public java.lang.Integer getReleasedflag() {
		return getInt("releasedflag");
	}

	public void setFilepath(java.lang.String filepath) {
		set("filepath", filepath);
	}
	
	public java.lang.String getFilepath() {
		return getStr("filepath");
	}

	public void setMustread(java.lang.Integer mustread) {
		set("mustread", mustread);
	}
	
	public java.lang.Integer getMustread() {
		return getInt("mustread");
	}

	public void setReleasetime(java.util.Date releasetime) {
		set("releasetime", releasetime);
	}
	
	public java.util.Date getReleasetime() {
		return get("releasetime");
	}

	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
