package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicReportcorrectRules<M extends BaseDicReportcorrectRules<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
	}
	
	public java.lang.String getKeyword() {
		return getStr("keyword");
	}

	public void setRules(java.lang.String rules) {
		set("rules", rules);
	}
	
	public java.lang.String getRules() {
		return getStr("rules");
	}

	public void setWarning(java.lang.String warning) {
		set("warning", warning);
	}
	
	public java.lang.String getWarning() {
		return getStr("warning");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
