package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResearchTestgroupData<M extends BaseResearchTestgroupData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setFormId(java.lang.Integer formId) {
		set("form_id", formId);
	}
	
	public java.lang.Integer getFormId() {
		return getInt("form_id");
	}
	
	public void setFormName(java.lang.String formName) {
		set("form_name", formName);
	}
	
	public java.lang.String getFormName() {
		return getStr("form_name");
	}
	
	public void setGroupId(java.lang.Integer groupId) {
		set("group_id", groupId);
	}
	
	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}
	
	public void setReportid(java.lang.Integer reportid) {
		set("reportid", reportid);
	}
	
	public java.lang.Integer getReportid() {
		return getInt("reportid");
	}
	
	public void setHtml(java.lang.String html) {
		set("html", html);
	}
	
	public java.lang.String getHtml() {
		return getStr("html");
	}
	
	public void setPrintHtml(java.lang.String printHtml) {
		set("print_html", printHtml);
	}
	
	public java.lang.String getPrintHtml() {
		return getStr("print_html");
	}
	
	public void setPatientname(java.lang.String patientname) {
		set("patientname", patientname);
	}
	
	public java.lang.String getPatientname() {
		return getStr("patientname");
	}
	
	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}
	
	public void setPatientid(java.lang.String patientid) {
		set("patientid", patientid);
	}
	
	public java.lang.String getPatientid() {
		return getStr("patientid");
	}
	
	public void setAge(java.lang.Integer age) {
		set("age", age);
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}
	
	public void setAgeUnit(java.lang.String age_unit) {
		set("age_unit", age_unit);
	}
	
	public java.lang.String getAgeUnit() {
		return getStr("age_unit");
	}
	
	public void setBirthdate(java.lang.String birthdate) {
		set("birthdate", birthdate);
	}
	
	public java.lang.String getBirthdate() {
		return getStr("birthdate");
	}
	
	public void setStudyid(java.lang.String studyid) {
		set("studyid", studyid);
	}
	
	public java.lang.String getStudyid() {
		return getStr("studyid");
	}
	
	public void setModalityType(java.lang.String modalityType) {
		set("modality_type", modalityType);
	}
	
	public java.lang.String getModalityType() {
		return getStr("modality_type");
	}
	
	public void setStudyitems(java.lang.String studyitems) {
		set("studyitems", studyitems);
	}
	
	public java.lang.String getStudyitems() {
		return getStr("studyitems");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}
	
	public void setDeleted(java.lang.String deleted) {
		set("deleted", deleted);
	}
	
	public java.lang.String getDeleted() {
		return getStr("deleted");
	}
	
	public void setStudyDatetime(java.util.Date study_datetime) {
		set("study_datetime", study_datetime);
	}
	
	public java.util.Date getStudyDatetime() {
		return get("study_datetime");
	}
	
	public void setErrorImport(java.lang.String error_import) {
		set("error_import", error_import);
	}
	
	public java.lang.String getErrorImport() {
		return getStr("error_import");
	}
	
	public void setAudittime(java.util.Date audittime) {
		set("audittime", audittime);
	}
	
	public java.util.Date getAudittime() {
		return get("audittime");
	}
	
	public void setAuditor(java.lang.Integer auditor) {
		set("auditor", auditor);
	}
	
	public java.lang.Integer getAuditor() {
		return getInt("auditor");
	}
	
}
