package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudyMethodTemplate<M extends BaseStudyMethodTemplate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public void setParentid(java.lang.Integer parentid) {
		set("parentid", parentid);
	}
	
	public java.lang.Integer getParentid() {
		return getInt("parentid");
	}

	public void setModalityid(java.lang.Integer modalityid) {
		set("modalityid", modalityid);
	}
	
	public java.lang.Integer getModalityid() {
		return getInt("modalityid");
	}

	public void setNodename(java.lang.String nodename) {
		set("nodename", nodename);
	}
	
	public java.lang.String getNodename() {
		return getStr("nodename");
	}

	public void setStudymethod(java.lang.String studymethod) {
		set("studymethod", studymethod);
	}
	
	public java.lang.String getStudymethod() {
		return getStr("studymethod");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setIspublic(java.lang.String ispublic) {
		set("ispublic", ispublic);
	}
	
	public java.lang.String getIspublic() {
		return getStr("ispublic");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setModalitytype(java.lang.String modalitytype) {
		set("modalitytype", modalitytype);
	}
	
	public java.lang.String getModalitytype() {
		return getStr("modalitytype");
	}
	
	public void setCode(java.lang.String code) {
        set("code", code);
    }
    
    public java.lang.String getCode() {
        return getStr("code");
    }
    
    public void setNodeNameSpell(java.lang.String nodenamespell) {
        set("nodenamespell", nodenamespell);
    }
    
    public java.lang.String getNodeNameSpell() {
        return getStr("nodenamespell");
    }

}
