package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudyImage<M extends BaseStudyImage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setOrderId(java.lang.Integer orderid) {
		set("orderid", orderid);
	}
	
	public java.lang.Integer getOrderId() {
		return getInt("orderid");
	}

	public void setStudyid(java.lang.String studyid) {
		set("studyid", studyid);
	}
	
	public java.lang.String getStudyid() {
		return getStr("studyid");
	}

	public void setImg1(java.lang.String img1) {
		set("img1", img1);
	}
	
	public java.lang.String getImg1() {
		return getStr("img1");
	}

	public void setImg2(java.lang.String img2) {
		set("img2", img2);
	}
	
	public java.lang.String getImg2() {
		return getStr("img2");
	}

	public void setImg3(java.lang.String img3) {
		set("img3", img3);
	}
	
	public java.lang.String getImg3() {
		return getStr("img3");
	}

	public void setImg4(java.lang.String img4) {
		set("img4", img4);
	}
	
	public java.lang.String getImg4() {
		return getStr("img4");
	}

	public void setImg5(java.lang.String img5) {
		set("img5", img5);
	}
	
	public java.lang.String getImg5() {
		return getStr("img5");
	}

	public void setImg6(java.lang.String img6) {
		set("img6", img6);
	}
	
	public java.lang.String getImg6() {
		return getStr("img6");
	}

	public void setImg7(java.lang.String img7) {
		set("img7", img7);
	}
	
	public java.lang.String getImg7() {
		return getStr("img7");
	}

	public void setImg8(java.lang.String img8) {
		set("img8", img8);
	}
	
	public java.lang.String getImg8() {
		return getStr("img8");
	}

	public void setImg9(java.lang.String img9) {
		set("img9", img9);
	}
	
	public java.lang.String getImg9() {
		return getStr("img9");
	}

	public void setImg10(java.lang.String img10) {
		set("img10", img10);
	}
	
	public java.lang.String getImg10() {
		return getStr("img10");
	}

}
