package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResearchJoingroupRuleItem<M extends BaseResearchJoingroupRuleItem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setRuleId(java.lang.Integer rule_id) {
		set("rule_id", rule_id);
	}
	
	public java.lang.Integer getRuleId() {
		return getInt("rule_id");
	}
	
	public void setMatchingField(java.lang.String matchingField) {
		set("matching_field", matchingField);
	}
	
	public java.lang.String getMatchingField() {
		return getStr("matching_field");
	}
	
	public void setMatchingName(java.lang.String matchingName) {
		set("matching_name", matchingName);
	}
	
	public java.lang.String getMatchingName() {
		return getStr("matching_name");
	}
	
	public void setMatchingValue(java.lang.String matchingValue) {
		set("matching_value", matchingValue);
	}
	
	public java.lang.String getMatchingValue() {
		return getStr("matching_value");
	}
	
}
