package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicModality<M extends BaseDicModality<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setDepartmentid(java.lang.Integer departmentid) {
		set("departmentid", departmentid);
	}
	
	public java.lang.Integer getDepartmentid() {
		return getInt("departmentid");
	}

	public void setModalityName(java.lang.String modalityName) {
		set("modality_name", modalityName);
	}
	
	public java.lang.String getModalityName() {
		return getStr("modality_name");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setRole(java.lang.String role) {
		set("role", role);
	}
	
	public java.lang.String getRole() {
		return getStr("role");
	}

	public void setManufacturer(java.lang.String manufacturer) {
		set("manufacturer", manufacturer);
	}
	
	public java.lang.String getManufacturer() {
		return getStr("manufacturer");
	}

	public void setModel(java.lang.String model) {
		set("model", model);
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}

	public void setHostname(java.lang.String hostname) {
		set("hostname", hostname);
	}
	
	public java.lang.String getHostname() {
		return getStr("hostname");
	}

	public void setInstitutionid(java.lang.Integer institutionid) {
		set("institutionid", institutionid);
	}
	
	public java.lang.Integer getInstitutionid() {
		return getInt("institutionid");
	}

	public void setStoragescu(java.lang.String storagescu) {
		set("storagescu", storagescu);
	}
	
	public java.lang.String getStoragescu() {
		return getStr("storagescu");
	}

	public void setStoragescp(java.lang.String storagescp) {
		set("storagescp", storagescp);
	}
	
	public java.lang.String getStoragescp() {
		return getStr("storagescp");
	}

	public void setStoragescpport(java.lang.Integer storagescpport) {
		set("storagescpport", storagescpport);
	}
	
	public java.lang.Integer getStoragescpport() {
		return getInt("storagescpport");
	}

	public void setStoragecmtscu(java.lang.String storagecmtscu) {
		set("storagecmtscu", storagecmtscu);
	}
	
	public java.lang.String getStoragecmtscu() {
		return getStr("storagecmtscu");
	}

	public void setStoragecmtscp(java.lang.String storagecmtscp) {
		set("storagecmtscp", storagecmtscp);
	}
	
	public java.lang.String getStoragecmtscp() {
		return getStr("storagecmtscp");
	}

	public void setStoragecmtscpport(java.lang.Integer storagecmtscpport) {
		set("storagecmtscpport", storagecmtscpport);
	}
	
	public java.lang.Integer getStoragecmtscpport() {
		return getInt("storagecmtscpport");
	}

	public void setQrscu(java.lang.String qrscu) {
		set("qrscu", qrscu);
	}
	
	public java.lang.String getQrscu() {
		return getStr("qrscu");
	}

	public void setQrscp(java.lang.String qrscp) {
		set("qrscp", qrscp);
	}
	
	public java.lang.String getQrscp() {
		return getStr("qrscp");
	}

	public void setQrscpport(java.lang.Integer qrscpport) {
		set("qrscpport", qrscpport);
	}
	
	public java.lang.Integer getQrscpport() {
		return getInt("qrscpport");
	}

	public void setPrintscu(java.lang.String printscu) {
		set("printscu", printscu);
	}
	
	public java.lang.String getPrintscu() {
		return getStr("printscu");
	}

	public void setPrintscp(java.lang.String printscp) {
		set("printscp", printscp);
	}
	
	public java.lang.String getPrintscp() {
		return getStr("printscp");
	}

	public void setPrintport(java.lang.Integer printport) {
		set("printport", printport);
	}
	
	public java.lang.Integer getPrintport() {
		return getInt("printport");
	}

	public void setLocation(java.lang.String location) {
		set("location", location);
	}
	
	public java.lang.String getLocation() {
		return getStr("location");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setGroupid(java.lang.Integer groupid) {
		set("groupid", groupid);
	}
	
	public java.lang.Integer getGroupid() {
		return getInt("groupid");
	}

	public void setAveragetime(java.lang.Integer averagetime) {
		set("averagetime", averagetime);
	}
	
	public java.lang.Integer getAveragetime() {
		return getInt("averagetime");
	}

	public void setReportAlertHour(java.lang.Integer reportAlertHour) {
		set("report_alert_hour", reportAlertHour);
	}
	
	public java.lang.Integer getReportAlertHour() {
		return getInt("report_alert_hour");
	}

	public void setReportAlertMinute(java.lang.Integer reportAlertMinute) {
		set("report_alert_minute", reportAlertMinute);
	}
	
	public java.lang.Integer getReportAlertMinute() {
		return getInt("report_alert_minute");
	}

	public void setWorkdayOfWorktime(java.lang.String workdayOfWorktime) {
		set("workday_of_worktime", workdayOfWorktime);
	}
	
	public java.lang.String getWorkdayOfWorktime() {
		return getStr("workday_of_worktime");
	}

	public void setSaturdayOfWorktime(java.lang.String saturdayOfWorktime) {
		set("saturday_of_worktime", saturdayOfWorktime);
	}
	
	public java.lang.String getSaturdayOfWorktime() {
		return getStr("saturday_of_worktime");
	}

	public void setSundayOfWorktime(java.lang.String sundayOfWorktime) {
		set("sunday_of_worktime", sundayOfWorktime);
	}
	
	public java.lang.String getSundayOfWorktime() {
		return getStr("sunday_of_worktime");
	}

	public void setWorklistscp(java.lang.String worklistscp) {
		set("worklistscp", worklistscp);
	}
	
	public java.lang.String getWorklistscp() {
		return getStr("worklistscp");
	}

	public void setWorklistscu(java.lang.String worklistscu) {
		set("worklistscu", worklistscu);
	}
	
	public java.lang.String getWorklistscu() {
		return getStr("worklistscu");
	}

	public void setWorklistport(java.lang.Integer worklistport) {
		set("worklistport", worklistport);
	}
	
	public java.lang.Integer getWorklistport() {
		return getInt("worklistport");
	}

	public void setWorkingState(java.lang.Integer workingState) {
		set("working_state", workingState);
	}
	
	public java.lang.Integer getWorkingState() {
		return getInt("working_state");
	}

	public void setDeleted(java.lang.String deleted) {
		set("deleted", deleted);
	}
	
	public java.lang.String getDeleted() {
		return getStr("deleted");
	}

	public void setAppointmentTime(java.lang.Integer appointmentTime) {
		set("appointment_time", appointmentTime);
	}
	
	public java.lang.Integer getAppointmentTime() {
		return getInt("appointment_time");
	}

	public void setAppointmentNumber(java.lang.Integer appointmentNumber) {
		set("appointment_number", appointmentNumber);
	}
	
	public java.lang.Integer getAppointmentNumber() {
		return getInt("appointment_number");
	}

	public void setAdvanceHour(java.lang.Integer advanceHour) {
		set("advance_hour", advanceHour);
	}
	
	public java.lang.Integer getAdvanceHour() {
		return getInt("advance_hour");
	}

	public void setAdvanceMinute(java.lang.Integer advanceMinute) {
		set("advance_minute", advanceMinute);
	}
	
	public java.lang.Integer getAdvanceMinute() {
		return getInt("advance_minute");
	}

	public void setCharacter(java.lang.String character) {
		set("character", character);
	}
	
	public java.lang.String getCharacter() {
		return getStr("character");
	}

}
