package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserShortcutConfig<M extends BaseUserShortcutConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}
	
	public void setModality(java.lang.String modality) {
		set("modality", modality);
	}
	
	public java.lang.String getModality() {
		return getStr("modality");
	}
	
	public void setKeyCode(java.lang.String keyCode) {
		set("keyCode", keyCode);
	}
	
	public java.lang.String getKeyCode() {
		return getStr("keyCode");
	}
	
	public void setTemplateId(java.lang.Integer templateId) {
		set("template_id", templateId);
	}
	
	public java.lang.Integer getTemplateId() {
		return getInt("template_id");
	}
	
}
