package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReporttemplatenode<M extends BaseReporttemplatenode<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNodename(java.lang.String nodename) {
		set("nodename", nodename);
	}

	public java.lang.String getNodename() {
		return get("nodename");
	}

	public void setModality(java.lang.String modality) {
		set("modality", modality);
	}

	public java.lang.String getModality() {
		return get("modality");
	}

	public void setParent(java.lang.Integer parent) {
		set("parent", parent);
	}

	public java.lang.Integer getParent() {
		return get("parent");
	}

	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}

	public java.lang.Integer getCreator() {
		return get("creator");
	}

	public void setIspublic(java.lang.String ispublic) {
		set("ispublic", ispublic);
	}

	public java.lang.String getIspublic() {
		return get("ispublic");
	}

}
