package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudyMaterialDefault<M extends BaseStudyMaterialDefault<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setModalityid(java.lang.Integer modalityid) {
		set("modalityid", modalityid);
	}
	
	public java.lang.Integer getModalityid() {
		return getInt("modalityid");
	}

	public void setExposurenum(java.lang.Integer exposurenum) {
		set("exposurenum", exposurenum);
	}
	
	public java.lang.Integer getExposurenum() {
		return getInt("exposurenum");
	}

	public void setFilmnum(java.lang.Integer filmnum) {
		set("filmnum", filmnum);
	}
	
	public java.lang.Integer getFilmnum() {
		return getInt("filmnum");
	}

	public void setContrastagent(java.lang.String contrastagent) {
		set("contrastagent", contrastagent);
	}
	
	public java.lang.String getContrastagent() {
		return getStr("contrastagent");
	}

	public void setContrastagentdose(java.lang.Integer contrastagentdose) {
		set("contrastagentdose", contrastagentdose);
	}
	
	public java.lang.Integer getContrastagentdose() {
		return getInt("contrastagentdose");
	}

	public void setTechnicianid(java.lang.Integer technicianid) {
		set("technicianid", technicianid);
	}
	
	public java.lang.Integer getTechnicianid() {
		return getInt("technicianid");
	}

	public void setTechnician(java.lang.String technician) {
		set("technician", technician);
	}
	
	public java.lang.String getTechnician() {
		return getStr("technician");
	}

	public void setNurseid(java.lang.Integer nurseid) {
		set("nurseid", nurseid);
	}
	
	public java.lang.Integer getNurseid() {
		return getInt("nurseid");
	}

	public void setNurse(java.lang.String nurse) {
		set("nurse", nurse);
	}
	
	public java.lang.String getNurse() {
		return getStr("nurse");
	}

	public void setPhysicianid(java.lang.Integer physicianid) {
		set("physicianid", physicianid);
	}
	
	public java.lang.Integer getPhysicianid() {
		return getInt("physicianid");
	}

	public void setPhysician(java.lang.String physician) {
		set("physician", physician);
	}
	
	public java.lang.String getPhysician() {
		return getStr("physician");
	}

	public void setCost(java.math.BigDecimal cost) {
		set("cost", cost);
	}
	
	public java.math.BigDecimal getCost() {
		return get("cost");
	}

	public void setMethodtemplateid(java.lang.Integer methodtemplateid) {
		set("methodtemplateid", methodtemplateid);
	}
	
	public java.lang.Integer getMethodtemplateid() {
		return getInt("methodtemplateid");
	}

	public void setStudymethod(java.lang.String studymethod) {
		set("studymethod", studymethod);
	}
	
	public java.lang.String getStudymethod() {
		return getStr("studymethod");
	}

	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
