package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePreviousHistory<M extends BasePreviousHistory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStudyorderfk(java.lang.Integer studyorderfk) {
		set("studyorderfk", studyorderfk);
	}
	
	public java.lang.Integer getStudyorderfk() {
		return getInt("studyorderfk");
	}

	public void setStudyid(java.lang.String studyid) {
		set("studyid", studyid);
	}
	
	public java.lang.String getStudyid() {
		return getStr("studyid");
	}

	public void setInterrogationTime(java.util.Date interrogationTime) {
		set("interrogation_time", interrogationTime);
	}
	
	public java.util.Date getInterrogationTime() {
		return get("interrogation_time");
	}

	public void setDiabetes(java.lang.String diabetes) {
		set("diabetes", diabetes);
	}
	
	public java.lang.String getDiabetes() {
		return getStr("diabetes");
	}

	public void setHypertension(java.lang.String hypertension) {
		set("hypertension", hypertension);
	}
	
	public java.lang.String getHypertension() {
		return getStr("hypertension");
	}

	public void setFamilyTumor(java.lang.String familyTumor) {
		set("family_tumor", familyTumor);
	}
	
	public java.lang.String getFamilyTumor() {
		return getStr("family_tumor");
	}

	public void setRecentFeverHistory(java.lang.String recentFeverHistory) {
		set("recent_fever_history", recentFeverHistory);
	}
	
	public java.lang.String getRecentFeverHistory() {
		return getStr("recent_fever_history");
	}

	public void setRecentFeverDuration(java.lang.Integer recentFeverDuration) {
		set("recent_fever_duration", recentFeverDuration);
	}
	
	public java.lang.Integer getRecentFeverDuration() {
		return getInt("recent_fever_duration");
	}

	public void setCerebralInfarctionHistory(java.lang.String cerebralInfarctionHistory) {
		set("cerebral_infarction_history", cerebralInfarctionHistory);
	}
	
	public java.lang.String getCerebralInfarctionHistory() {
		return getStr("cerebral_infarction_history");
	}

	public void setCerebralVesselsHistory(java.lang.String cerebralVesselsHistory) {
		set("cerebral_vessels_history", cerebralVesselsHistory);
	}
	
	public java.lang.String getCerebralVesselsHistory() {
		return getStr("cerebral_vessels_history");
	}

	public void setRecentExamine(java.lang.String recentExamine) {
		set("recent_examine", recentExamine);
	}
	
	public java.lang.String getRecentExamine() {
		return getStr("recent_examine");
	}

	public void setRecentLeukocyteMedicine(java.lang.String recentLeukocyteMedicine) {
		set("recent_leukocyte_medicine", recentLeukocyteMedicine);
	}
	
	public java.lang.String getRecentLeukocyteMedicine() {
		return getStr("recent_leukocyte_medicine");
	}

	public void setTraumaDatetime(java.util.Date traumaDatetime) {
		set("trauma_datetime", traumaDatetime);
	}
	
	public java.util.Date getTraumaDatetime() {
		return get("trauma_datetime");
	}

	public void setTraumaPlace(java.lang.String traumaPlace) {
		set("trauma_place", traumaPlace);
	}
	
	public java.lang.String getTraumaPlace() {
		return getStr("trauma_place");
	}

	public void setTuberculosis(java.lang.String tuberculosis) {
		set("tuberculosis", tuberculosis);
	}
	
	public java.lang.String getTuberculosis() {
		return getStr("tuberculosis");
	}

	public void setSchistosomiasisHistory(java.lang.String schistosomiasisHistory) {
		set("schistosomiasis_history", schistosomiasisHistory);
	}
	
	public java.lang.String getSchistosomiasisHistory() {
		return getStr("schistosomiasis_history");
	}

	public void setHepatitisAndSclerosis(java.lang.String hepatitisAndSclerosis) {
		set("hepatitis_and_sclerosis", hepatitisAndSclerosis);
	}
	
	public java.lang.String getHepatitisAndSclerosis() {
		return getStr("hepatitis_and_sclerosis");
	}

	public void setHemorrhoidsHistory(java.lang.String hemorrhoidsHistory) {
		set("hemorrhoids_history", hemorrhoidsHistory);
	}
	
	public java.lang.String getHemorrhoidsHistory() {
		return getStr("hemorrhoids_history");
	}

	public void setSmokingHistory(java.lang.String smokingHistory) {
		set("smoking_history", smokingHistory);
	}
	
	public java.lang.String getSmokingHistory() {
		return getStr("smoking_history");
	}

	public void setOtherMedicalHistory(java.lang.String otherMedicalHistory) {
		set("other_medical_history", otherMedicalHistory);
	}
	
	public java.lang.String getOtherMedicalHistory() {
		return getStr("other_medical_history");
	}

	public void setCtAndMr(java.lang.Integer ctAndMr) {
		set("ctAndMr", ctAndMr);
	}
	
	public java.lang.Integer getCtAndMr() {
		return getInt("ctAndMr");
	}

	public void setPresentation(java.lang.Integer presentation) {
		set("presentation", presentation);
	}
	
	public java.lang.Integer getPresentation() {
		return getInt("presentation");
	}

	public void setUltrasonicEport(java.lang.Integer ultrasonicEport) {
		set("ultrasonic_eport", ultrasonicEport);
	}
	
	public java.lang.Integer getUltrasonicEport() {
		return getInt("ultrasonic_eport");
	}

	public void setGastroscopyReport(java.lang.Integer gastroscopyReport) {
		set("gastroscopy_report", gastroscopyReport);
	}
	
	public java.lang.Integer getGastroscopyReport() {
		return getInt("gastroscopy_report");
	}

	public void setEnteroscopyReport(java.lang.Integer enteroscopyReport) {
		set("enteroscopy_report", enteroscopyReport);
	}
	
	public java.lang.Integer getEnteroscopyReport() {
		return getInt("enteroscopy_report");
	}

	public void setNpgReport(java.lang.Integer npgReport) {
		set("npg_report", npgReport);
	}
	
	public java.lang.Integer getNpgReport() {
		return getInt("npg_report");
	}

	public void setLaryngoscopeReport(java.lang.Integer laryngoscopeReport) {
		set("laryngoscope_report", laryngoscopeReport);
	}
	
	public java.lang.Integer getLaryngoscopeReport() {
		return getInt("laryngoscope_report");
	}

	public void setTracheoscopeReport(java.lang.Integer tracheoscopeReport) {
		set("tracheoscope_report", tracheoscopeReport);
	}
	
	public java.lang.Integer getTracheoscopeReport() {
		return getInt("tracheoscope_report");
	}

	public void setOutPetReport(java.lang.Integer outPetReport) {
		set("out_PET_report", outPetReport);
	}
	
	public java.lang.Integer getOutPetReport() {
		return getInt("out_PET_report");
	}

	public void setInPetReport(java.lang.Integer inPetReport) {
		set("in_PET_report", inPetReport);
	}
	
	public java.lang.Integer getInPetReport() {
		return getInt("in_PET_report");
	}

	public void setDischargeSummary(java.lang.Integer dischargeSummary) {
		set("dischargeSummary", dischargeSummary);
	}
	
	public java.lang.Integer getDischargeSummary() {
		return getInt("dischargeSummary");
	}

	public void setOther(java.lang.Integer other) {
		set("other", other);
	}
	
	public java.lang.Integer getOther() {
		return getInt("other");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.util.Date getModifytime() {
		return get("modifytime");
	}

}
