package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInquiry<M extends BaseInquiry<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStudyorderfk(java.lang.Integer studyorderfk) {
		set("studyorderfk", studyorderfk);
	}
	
	public java.lang.Integer getStudyorderfk() {
		return getInt("studyorderfk");
	}

	public void setStudyid(java.lang.String studyid) {
		set("studyid", studyid);
	}
	
	public java.lang.String getStudyid() {
		return getStr("studyid");
	}

	public void setClinicaldiagnosis(java.lang.String clinicaldiagnosis) {
		set("clinicaldiagnosis", clinicaldiagnosis);
	}
	
	public java.lang.String getClinicaldiagnosis() {
		return getStr("clinicaldiagnosis");
	}

	public void setBriefhistory(java.lang.String briefhistory) {
		set("briefhistory", briefhistory);
	}
	
	public java.lang.String getBriefhistory() {
		return getStr("briefhistory");
	}

	public void setOperationdatetime(java.util.Date operationdatetime) {
		set("operationdatetime", operationdatetime);
	}
	
	public java.util.Date getOperationdatetime() {
		return get("operationdatetime");
	}

	public void setOperationmethod(java.lang.String operationmethod) {
		set("operationmethod", operationmethod);
	}
	
	public java.lang.String getOperationmethod() {
		return getStr("operationmethod");
	}

	public void setPathology(java.lang.String pathology) {
		set("pathology", pathology);
	}
	
	public java.lang.String getPathology() {
		return getStr("pathology");
	}

	public void setLastChemotherapyDatetime(java.util.Date lastChemotherapyDatetime) {
		set("last_chemotherapy_datetime", lastChemotherapyDatetime);
	}
	
	public java.util.Date getLastChemotherapyDatetime() {
		return get("last_chemotherapy_datetime");
	}

	public void setLastRadiotherapyDatetime(java.util.Date lastRadiotherapyDatetime) {
		set("last_radiotherapy_datetime", lastRadiotherapyDatetime);
	}
	
	public java.util.Date getLastRadiotherapyDatetime() {
		return get("last_radiotherapy_datetime");
	}

	public void setImageResult(java.lang.String imageResult) {
		set("image_result", imageResult);
	}
	
	public java.lang.String getImageResult() {
		return getStr("image_result");
	}

	public void setTumorRemoval(java.lang.String tumorRemoval) {
		set("tumor_removal", tumorRemoval);
	}
	
	public java.lang.String getTumorRemoval() {
		return getStr("tumor_removal");
	}

	public void setGallbladderDatetime(java.util.Date gallbladderDatetime) {
		set("gallbladder_datetime", gallbladderDatetime);
	}
	
	public java.util.Date getGallbladderDatetime() {
		return get("gallbladder_datetime");
	}

	public void setThyroidDatetime(java.util.Date thyroidDatetime) {
		set("thyroid_datetime", thyroidDatetime);
	}
	
	public java.util.Date getThyroidDatetime() {
		return get("thyroid_datetime");
	}

	public void setSpleenDatetime(java.util.Date spleenDatetime) {
		set("spleen_datetime", spleenDatetime);
	}
	
	public java.util.Date getSpleenDatetime() {
		return get("spleen_datetime");
	}

	public void setLeftKidneyDatetime(java.util.Date leftKidneyDatetime) {
		set("left_kidney_datetime", leftKidneyDatetime);
	}
	
	public java.util.Date getLeftKidneyDatetime() {
		return get("left_kidney_datetime");
	}

	public void setRightKidneyDatetime(java.util.Date rightKidneyDatetime) {
		set("right_kidney_datetime", rightKidneyDatetime);
	}
	
	public java.util.Date getRightKidneyDatetime() {
		return get("right_kidney_datetime");
	}

	public void setOtherInformation(java.lang.String otherInformation) {
		set("other_information", otherInformation);
	}
	
	public java.lang.String getOtherInformation() {
		return getStr("other_information");
	}

	public void setMenstruationConditions(java.lang.String menstruationConditions) {
		set("menstruation_conditions", menstruationConditions);
	}
	
	public java.lang.String getMenstruationConditions() {
		return getStr("menstruation_conditions");
	}

	public void setMenarcheAge(java.lang.Integer menarcheAge) {
		set("menarche_age", menarcheAge);
	}
	
	public java.lang.Integer getMenarcheAge() {
		return getInt("menarche_age");
	}

	public void setMenstruationPeriods(java.lang.Integer menstruationPeriods) {
		set("menstruation_periods", menstruationPeriods);
	}
	
	public java.lang.Integer getMenstruationPeriods() {
		return getInt("menstruation_periods");
	}

	public void setMenstruationDays(java.lang.Integer menstruationDays) {
		set("menstruation_days", menstruationDays);
	}
	
	public java.lang.Integer getMenstruationDays() {
		return getInt("menstruation_days");
	}

	public void setMenstruationRecent(java.lang.Integer menstruationRecent) {
		set("menstruation_recent", menstruationRecent);
	}
	
	public java.lang.Integer getMenstruationRecent() {
		return getInt("menstruation_recent");
	}

	public void setInterrogationTime(java.util.Date interrogationTime) {
		set("interrogation_time", interrogationTime);
	}
	
	public java.util.Date getInterrogationTime() {
		return get("interrogation_time");
	}

	public void setInterrogationDoctorId(java.lang.Integer interrogationDoctorId) {
		set("interrogation_doctor_id", interrogationDoctorId);
	}
	
	public java.lang.Integer getInterrogationDoctorId() {
		return getInt("interrogation_doctor_id");
	}

	public void setNuclide(java.lang.String nuclide) {
		set("nuclide", nuclide);
	}
	
	public java.lang.String getNuclide() {
		return getStr("nuclide");
	}

	public void setMedicine(java.lang.String medicine) {
		set("medicine", medicine);
	}
	
	public java.lang.String getMedicine() {
		return getStr("medicine");
	}

	public void setFastingGlucose(java.math.BigDecimal fastingGlucose) {
		set("fasting_glucose", fastingGlucose);
	}
	
	public java.math.BigDecimal getFastingGlucose() {
		return get("fasting_glucose");
	}

	public void setPrescribedDose(java.math.BigDecimal prescribedDose) {
		set("prescribed_dose", prescribedDose);
	}
	
	public java.math.BigDecimal getPrescribedDose() {
		return get("prescribed_dose");
	}

	public void setAdministrationMethod(java.lang.String administrationMethod) {
		set("administration_method", administrationMethod);
	}
	
	public java.lang.String getAdministrationMethod() {
		return getStr("administration_method");
	}

	public void setSpInjectionReq(java.lang.Integer spInjectionReq) {
		set("sp_injection_req", spInjectionReq);
	}
	
	public java.lang.Integer getSpInjectionReq() {
		return getInt("sp_injection_req");
	}

	public void setSpInspectionReq(java.lang.Integer spInspectionReq) {
		set("sp_inspection_req", spInspectionReq);
	}
	
	public java.lang.Integer getSpInspectionReq() {
		return getInt("sp_inspection_req");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.util.Date getModifytime() {
		return get("modifytime");
	}

}
