package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicOrgan<M extends BaseDicOrgan<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTreenameZh(java.lang.String treenameZh) {
		set("treename_zh", treenameZh);
	}
	
	public java.lang.String getTreenameZh() {
		return getStr("treename_zh");
	}

	public void setTreenameEn(java.lang.String treenameEn) {
		set("treename_en", treenameEn);
	}
	
	public java.lang.String getTreenameEn() {
		return getStr("treename_en");
	}

	public void setParentid(java.lang.Integer parentid) {
		set("parentid", parentid);
	}
	
	public java.lang.Integer getParentid() {
		return getInt("parentid");
	}

	public void setTypecode(java.lang.String typecode) {
		set("typecode", typecode);
	}
	
	public java.lang.String getTypecode() {
		return getStr("typecode");
	}
	
	public void setModality(java.lang.String modality) {
		set("modality", modality);
	}
	
	public java.lang.String getModality() {
		return getStr("modality");
	}

	public void setLevelnum(java.lang.Integer levelnum) {
		set("levelnum", levelnum);
	}
	
	public java.lang.Integer getLevelnum() {
		return getInt("levelnum");
	}
	
	public void setDeleted(java.lang.String deleted) {
		set("deleted", deleted);
	}

	public java.lang.String getDeleted() {
		return get("deleted");
	}
}
