package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResearchJoingroupApply<M extends BaseResearchJoingroupApply<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setProjectId(java.lang.Integer project_id) {
		set("project_id", project_id);
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}
	
	public void setGroupId(java.lang.Integer group_id) {
		set("group_id", group_id);
	}
	
	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
	public void setApplicant(java.lang.Integer applicant) {
		set("applicant", applicant);
	}
	
	public java.lang.Integer getApplicant() {
		return getInt("applicant");
	}
	
	public void setAppDatetime(java.util.Date app_datetime) {
		set("app_datetime", app_datetime);
	}
	
	public java.util.Date getAppDatetime() {
		return get("app_datetime");
	}
	
	public void setValidPeriod(java.util.Date valid_period) {
		set("valid_period", valid_period);
	}
	
	public java.util.Date getValidPeriod() {
		return get("valid_period");
	}
	
	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}
	
	public java.lang.String getReason() {
		return getStr("reason");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
}
