package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResearchJoingroupRule<M extends BaseResearchJoingroupRule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setRuleName(java.lang.String ruleName) {
		set("rule_name", ruleName);
	}
	
	public java.lang.String getRuleName() {
		return getStr("rule_name");
	}
	
	public void setProjectId(java.lang.Integer project_id) {
		set("project_id", project_id);
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}
	
	public void setGroupId(java.lang.Integer group_id) {
		set("group_id", group_id);
	}
	
	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}
	
}
