package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStatusColor<M extends BaseStatusColor<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setColor(java.lang.String color) {
		set("color", color);
	}
	
	public java.lang.String getColor() {
		return getStr("color");
	}

	public void setStatusCode(java.lang.String statusCode) {
		set("status_code", statusCode);
	}
	
	public java.lang.String getStatusCode() {
		return getStr("status_code");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

}
