package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResearchTestgroupForm<M extends BaseResearchTestgroupForm<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setGroupid(java.lang.Integer groupid) {
		set("groupid", groupid);
	}
	
	public java.lang.Integer getGroupid() {
		return getInt("groupid");
	}
	
	public void setFormid(java.lang.Integer formid) {
		set("formid", formid);
	}
	
	public java.lang.Integer getFormid() {
		return getInt("formid");
	}
	
}
