package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResearchUserRole<M extends BaseResearchUserRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setProjectId(java.lang.Integer project_id) {
		set("project_id", project_id);
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}
	
	public void setUserId(java.lang.Integer user_id) {
		set("user_id", user_id);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}
	
	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
}
