package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmergencyStudyitem<M extends BaseEmergencyStudyitem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setEmergencyid(java.lang.Integer emergencyid) {
		set("emergencyid", emergencyid);
	}
	
	public java.lang.Integer getEmergencyid() {
		return getInt("emergencyid");
	}

	public void setModality(java.lang.String modality) {
		set("modality", modality);
	}
	
	public java.lang.String getModality() {
		return getStr("modality");
	}
	
	public void setItemId(java.lang.Integer itemId) {
		set("item_id", itemId);
	}
	
	public java.lang.Integer getItemId() {
		return getInt("item_id");
	}

	public void setItemCode(java.lang.String itemCode) {
		set("item_code", itemCode);
	}
	
	public java.lang.String getItemCode() {
		return getStr("item_code");
	}

	public void setItemName(java.lang.String itemName) {
		set("item_name", itemName);
	}
	
	public java.lang.String getItemName() {
		return getStr("item_name");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setRealprice(java.math.BigDecimal realprice) {
		set("realprice", realprice);
	}
	
	public java.math.BigDecimal getRealprice() {
		return get("realprice");
	}

	public void setChargeStatus(java.lang.String chargeStatus) {
		set("charge_status", chargeStatus);
	}
	
	public java.lang.String getChargeStatus() {
		return getStr("charge_status");
	}

	public void setOrgan(java.lang.Integer organ) {
		set("organ", organ);
	}
	
	public java.lang.Integer getOrgan() {
		return getInt("organ");
	}

	public void setSuborgan(java.lang.Integer suborgan) {
		set("suborgan", suborgan);
	}
	
	public java.lang.Integer getSuborgan() {
		return getInt("suborgan");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
