package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSyngoviasrdata<M extends BaseSyngoviasrdata<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStudyid(java.lang.String studyid) {
		set("studyid", studyid);
	}
	
	public java.lang.String getStudyid() {
		return getStr("studyid");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setCodesystemname(java.lang.String codesystemname) {
		set("codesystemname", codesystemname);
	}
	
	public java.lang.String getCodesystemname() {
		return getStr("codesystemname");
	}

	public void setCodedisplayname(java.lang.String codedisplayname) {
		set("codedisplayname", codedisplayname);
	}
	
	public java.lang.String getCodedisplayname() {
		return getStr("codedisplayname");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
	public void setValuecode(java.lang.String valuecode) {
		set("valuecode", valuecode);
	}
	
	public java.lang.String getValuecode() {
		return getStr("valuecode");
	}

	public void setValuecodesystemname(java.lang.String valuecodesystemname) {
		set("valuecodesystemname", valuecodesystemname);
	}
	
	public java.lang.String getValuecodesystemname() {
		return getStr("valuecodesystemname");
	}
	
	public void setValuedisplayname(java.lang.String valuedisplayname) {
		set("valuedisplayname", valuedisplayname);
	}
	
	public java.lang.String getValuedisplayname() {
		return getStr("valuedisplayname");
	}
	public void setViaVersion(java.lang.String via_version) {
		set("via_version", via_version);
	}
	
	public java.lang.String getViaVersion() {
		return getStr("via_version");
	}
	public void setSource(java.lang.Integer source) {
		set("source", source);
	}
	
	public java.lang.Integer getSource() {
		return getInt("source");
	}
}
