package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicInstitutionRole<M extends BaseDicInstitutionRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setInstitutionid(java.lang.Integer institutionid) {
		set("institutionid", institutionid);
	}
	
	public java.lang.Integer getInstitutionid() {
		return getInt("institutionid");
	}

	public void setRoleid(java.lang.Integer roleid) {
		set("roleid", roleid);
	}
	
	public java.lang.Integer getRoleid() {
		return getInt("roleid");
	}

}
