package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReporttemplate<M extends BaseReporttemplate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNodeid(java.lang.Integer nodeid) {
		set("nodeid", nodeid);
	}

	public java.lang.Integer getNodeid() {
		return get("nodeid");
	}

	public void setIspublic(java.lang.String ispublic) {
		set("ispublic", ispublic);
	}

	public java.lang.String getIspublic() {
		return get("ispublic");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}
	
	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}
	
	public void setStudymethod(java.lang.String studymethod) {
		set("studymethod", studymethod);
	}

	public java.lang.String getStudymethod() {
		return get("studymethod");
	}

	public void setDesccontent(java.lang.String desccontent) {
		set("desccontent", desccontent);
	}

	public java.lang.String getDesccontent() {
		return get("desccontent");
	}

	public void setDesccontentHtml(java.lang.String desccontentHtml) {
		set("desccontent_html", desccontentHtml);
	}

	public java.lang.String getDesccontentHtml() {
		return get("desccontent_html");
	}

	public void setResultcontent(java.lang.String resultcontent) {
		set("resultcontent", resultcontent);
	}

	public java.lang.String getResultcontent() {
		return get("resultcontent");
	}

	public void setResultcontentHtml(java.lang.String resultcontentHtml) {
		set("resultcontent_html", resultcontentHtml);
	}

	public java.lang.String getResultcontentHtml() {
		return get("resultcontent_html");
	}
	
	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}

	public java.lang.Integer getCreator() {
		return get("creator");
	}
	
	public void setCreatorName(String creatorName) {
		set("creator_name",creatorName);
	}
	public String getCreatorName() {
		return get("creator_name");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}

	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
