package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAe<M extends BaseAe<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAet(java.lang.String aet) {
		set("aet", aet);
	}
	
	public java.lang.String getAet() {
		return getStr("aet");
	}

	public void setHostname(java.lang.String hostname) {
		set("hostname", hostname);
	}
	
	public java.lang.String getHostname() {
		return getStr("hostname");
	}

	public void setPort(java.lang.Integer port) {
		set("port", port);
	}
	
	public java.lang.Integer getPort() {
		return getInt("port");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setAegroup(java.lang.String aegroup) {
		set("aegroup", aegroup);
	}
	
	public java.lang.String getAegroup() {
		return getStr("aegroup");
	}

	public void setAedesc(java.lang.String aedesc) {
		set("aedesc", aedesc);
	}
	
	public java.lang.String getAedesc() {
		return getStr("aedesc");
	}

	public void setStationname(java.lang.String stationname) {
		set("stationname", stationname);
	}
	
	public java.lang.String getStationname() {
		return getStr("stationname");
	}

	public void setInstitution(java.lang.String institution) {
		set("institution", institution);
	}
	
	public java.lang.String getInstitution() {
		return getStr("institution");
	}

	public void setDepartment(java.lang.String department) {
		set("department", department);
	}
	
	public java.lang.String getDepartment() {
		return getStr("department");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

}
