package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrinttemplate<M extends BasePrinttemplate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setTemplateName(java.lang.String templateName) {
		set("template_name", templateName);
	}
	
	public java.lang.String getTemplateName() {
		return getStr("template_name");
	}

	public void setModalityType(java.lang.String modalityType) {
		set("modality_type", modalityType);
	}
	
	public java.lang.String getModalityType() {
		return getStr("modality_type");
	}
	
	public void setExamitemId(java.lang.Integer examitem_id) {
		set("examitem_id", examitem_id);
	}
	
	public java.lang.Integer getExamitemId() {
		return getInt("examitem_id");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

}
