package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReporticd<M extends BaseReporticd<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setReportid(java.lang.Integer reportid) {
		set("reportid", reportid);
	}
	
	public java.lang.Integer getReportid() {
		return getInt("reportid");
	}

	public void setIcdId(java.lang.String icdId) {
		set("icd_id", icdId);
	}
	
	public java.lang.String getIcdId() {
		return getStr("icd_id");
	}

	public void setIcdCode(java.lang.String icdCode) {
		set("icd_code", icdCode);
	}
	
	public java.lang.String getIcdCode() {
		return getStr("icd_code");
	}

	public void setIcdSubcode(java.lang.String icdSubcode) {
		set("icd_subcode", icdSubcode);
	}
	
	public java.lang.String getIcdSubcode() {
		return getStr("icd_subcode");
	}

	public void setIcdName(java.lang.String icdName) {
		set("icd_name", icdName);
	}
	
	public java.lang.String getIcdName() {
		return getStr("icd_name");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
