package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSyngoviaimage<M extends BaseSyngoviaimage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setPatientid(java.lang.String patientid) {
		set("patientid", patientid);
	}
	
	public java.lang.String getPatientid() {
		return getStr("patientid");
	}
	
	public void setStudyinsuid(java.lang.String studyinsuid) {
		set("studyinsuid", studyinsuid);
	}
	
	public java.lang.String getStudyinsuid() {
		return getStr("studyinsuid");
	}

	public void setStudyid(java.lang.String studyid) {
		set("studyid", studyid);
	}
	
	public java.lang.String getStudyid() {
		return getStr("studyid");
	}

	public void setImagefile(java.lang.String imagefile) {
		set("imagefile", imagefile);
	}
	
	public java.lang.String getImagefile() {
		return getStr("imagefile");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
	public void setImageid(java.lang.String imageid) {
		set("imageid", imageid);
	}
	
	public java.lang.String getImageid() {
		return getStr("imageid");
	}

	public void setOrderby(java.lang.Integer orderby) {
		set("orderby", orderby);
	}
	
	public java.lang.Integer getOrderby() {
		return getInt("orderby");
	}
	public void setDelflag(java.lang.Integer delflag) {
		set("delflag", delflag);
	}
	
	public java.lang.Integer getDelflag() {
		return getInt("delflag");
	}
	
	public void setImgDesc(java.lang.String img_desc) {
		set("img_desc", img_desc);
	}
	
	public java.lang.String getImgDesc() {
		return getStr("img_desc");
	}
	public void setSource(java.lang.Integer source) {
		set("source", source);
	}
	
	public java.lang.Integer getSource() {
		return getInt("source");
	}
}
