package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdmission<M extends BaseAdmission<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPatientidfk(java.lang.Integer patientidfk) {
		set("patientidfk", patientidfk);
	}
	
	public java.lang.Integer getPatientidfk() {
		return getInt("patientidfk");
	}

	public void setAdmissionid(java.lang.String admissionid) {
		set("admissionid", admissionid);
	}
	
	public java.lang.String getAdmissionid() {
		return getStr("admissionid");
	}

	public void setPatientsource(java.lang.String patientsource) {
		set("patientsource", patientsource);
	}
	
	public java.lang.String getPatientsource() {
		return getStr("patientsource");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public void setAgeunit(java.lang.String ageunit) {
		set("ageunit", ageunit);
	}
	
	public java.lang.String getAgeunit() {
		return getStr("ageunit");
	}

	public void setOutno(java.lang.String outno) {
		set("outno", outno);
	}
	
	public java.lang.String getOutno() {
		return getStr("outno");
	}

	public void setInno(java.lang.String inno) {
		set("inno", inno);
	}
	
	public java.lang.String getInno() {
		return getStr("inno");
	}

	public void setCardno(java.lang.String cardno) {
		set("cardno", cardno);
	}
	
	public java.lang.String getCardno() {
		return getStr("cardno");
	}

	public void setWardno(java.lang.String wardno) {
		set("wardno", wardno);
	}
	
	public java.lang.String getWardno() {
		return getStr("wardno");
	}

	public void setBedno(java.lang.String bedno) {
		set("bedno", bedno);
	}
	
	public java.lang.String getBedno() {
		return getStr("bedno");
	}

	public void setAdmDate(java.lang.String admDate) {
		set("adm_date", admDate);
	}
	
	public java.lang.String getAdmDate() {
		return getStr("adm_date");
	}

	public void setDisDate(java.lang.String disDate) {
		set("dis_date", disDate);
	}
	
	public java.lang.String getDisDate() {
		return getStr("dis_date");
	}

	public void setAdmissionremark(java.lang.String admissionremark) {
		set("admissionremark", admissionremark);
	}
	
	public java.lang.String getAdmissionremark() {
		return getStr("admissionremark");
	}

	public void setSubjective(java.lang.String subjective) {
		set("subjective", subjective);
	}
	
	public java.lang.String getSubjective() {
		return getStr("subjective");
	}

	public void setAdmittingdiagnosis(java.lang.String admittingdiagnosis) {
		set("admittingdiagnosis", admittingdiagnosis);
	}
	
	public java.lang.String getAdmittingdiagnosis() {
		return getStr("admittingdiagnosis");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.util.Date getModifytime() {
		return get("modifytime");
	}

}
