package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChatMessage<M extends BaseChatMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setFromid(java.lang.Integer fromid) {
		set("fromid", fromid);
	}
	
	public java.lang.Integer getFromid() {
		return getInt("fromid");
	}

	public void setToid(java.lang.Integer toid) {
		set("toid", toid);
	}
	
	public java.lang.Integer getToid() {
		return getInt("toid");
	}

	public void setMsgcontent(java.lang.String msgcontent) {
		set("msgcontent", msgcontent);
	}
	
	public java.lang.String getMsgcontent() {
		return getStr("msgcontent");
	}

	public void setSourcetype(java.lang.String sourcetype) {
		set("sourcetype", sourcetype);
	}
	
	public java.lang.String getSourcetype() {
		return getStr("sourcetype");
	}

	public void setIsoffline(java.lang.Integer isoffline) {
		set("isoffline", isoffline);
	}
	
	public java.lang.Integer getIsoffline() {
		return getInt("isoffline");
	}

	public void setMsgtype(java.lang.Integer msgtype) {
		set("msgtype", msgtype);
	}
	
	public java.lang.Integer getMsgtype() {
		return getInt("msgtype");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
