package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChatGroupMsg<M extends BaseChatGroupMsg<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setMsgid(java.lang.Long msgid) {
		set("msgid", msgid);
	}
	
	public java.lang.Long getMsgid() {
		return getLong("msgid");
	}

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public void setGroupid(java.lang.Integer groupid) {
		set("groupid", groupid);
	}
	
	public java.lang.Integer getGroupid() {
		return getInt("groupid");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
