package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudy<M extends BaseStudy<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setPatientfk(java.lang.Integer patientfk) {
		set("patientfk", patientfk);
	}
	
	public java.lang.Integer getPatientfk() {
		return getInt("patientfk");
	}
	
	public void setStudyorderfk(java.lang.Integer studyorderfk) {
		set("studyorderfk", studyorderfk);
	}
	
	public java.lang.Integer getStudyorderfk() {
		return getInt("studyorderfk");
	}
	
	public void setModality(java.lang.String modality) {
		set("modality", modality);
	}
	
	public java.lang.String getModality() {
		return getStr("modality");
	}
	
	public void setTechnicianid(java.lang.Integer technicianid) {
		set("technicianid", technicianid);
	}
	
	public java.lang.Integer getTechnicianid() {
		return getInt("technicianid");
	}
	
	public void setTechnician(java.lang.String technician) {
		set("technician", technician);
	}
	
	public java.lang.String getTechnician() {
		return getStr("technician");
	}
	
	public void setNurseid(java.lang.Integer nurseid) {
		set("nurseid", nurseid);
	}
	
	public java.lang.Integer getNurseid() {
		return getInt("nurseid");
	}
	
	public void setNurse(java.lang.String nurse) {
		set("nurse", nurse);
	}
	
	public java.lang.String getNurse() {
		return getStr("nurse");
	}
	
	public void setCost(java.math.BigDecimal cost) {
		set("cost", cost);
	}
	
	public java.math.BigDecimal getCost() {
		return get("cost");
	}
	
	public void setPhysicianid(java.lang.Integer physicianid) {
		set("physicianid", physicianid);
	}
	
	public java.lang.Integer getPhysicianid() {
		return getInt("physicianid");
	}
	
	public void setPhysician(java.lang.String physician) {
		set("physician", physician);
	}
	
	public java.lang.String getPhysician() {
		return getStr("physician");
	}
	
	public void setStudymethod(java.lang.String studymethod) {
		set("studymethod", studymethod);
	}
	
	public java.lang.String getStudymethod() {
		return getStr("studymethod");
	}
	
	public void setReexaminereason(java.lang.String reexaminereason) {
		set("reexaminereason", reexaminereason);
	}
	
	public java.lang.String getReexaminereason() {
		return getStr("reexaminereason");
	}
	
	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}
	
	public void setOnEquipmentTime(java.util.Date on_equipment_time) {
		set("on_equipment_time", on_equipment_time);
	}
	
	public java.util.Date getOnEquipmentTime() {
		return get("on_equipment_time");
	}
	
	public void setExamPollution(java.lang.String exam_pollution) {
		set("exam_pollution", exam_pollution);
	}
	
	public java.lang.String getExamPollution() {
		return getStr("exam_pollution");
	}
	
	public void setDelayedAcquisition(java.lang.Integer delayedAcquisition) {
		set("delayed_acquisition", delayedAcquisition);
	}
	
	public java.lang.Integer getDelayedAcquisition() {
		return getInt("delayed_acquisition");
	}
	
	public void setDelayedAcquisition1(java.lang.Integer delayedAcquisition1) {
		set("delayed_acquisition1", delayedAcquisition1);
	}
	
	public java.lang.Integer getDelayedAcquisition1() {
		return getInt("delayed_acquisition1");
	}
	
	public void setDelayedAcquisitionTime(java.util.Date delayedAcquisitionTime) {
		set("delayed_acquisition_time", delayedAcquisitionTime);
	}
	
	public java.util.Date getDelayedAcquisitionTime() {
		return get("delayed_acquisition_time");
	}
	
	public void setDelayedAcquisitionTime1(java.util.Date delayedAcquisitionTime1) {
		set("delayed_acquisition_time1", delayedAcquisitionTime1);
	}
	
	public java.util.Date getDelayedAcquisitionTime1() {
		return get("delayed_acquisition_time1");
	}
	
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
}
