package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeptSubscriptionRule<M extends BaseDeptSubscriptionRule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public void setEmployeeid(java.lang.Integer employeeid) {
		set("employeeid", employeeid);
	}
	
	public java.lang.Integer getEmployeeid() {
		return getInt("employeeid");
	}

	public void setModalities(java.lang.String modalities) {
		set("modalities", modalities);
	}
	
	public java.lang.String getModalities() {
		return getStr("modalities");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
