package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStock<M extends BaseStock<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setGoodsId(java.lang.Integer goodsId) {
		set("goods_id", goodsId);
	}
	
	public java.lang.Integer getGoodsId() {
		return getInt("goods_id");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
	}
	
	public java.lang.String getGoodsName() {
		return getStr("goods_name");
	}

	public void setComLot(java.lang.String comLot) {
		set("com_lot", comLot);
	}
	
	public java.lang.String getComLot() {
		return getStr("com_lot");
	}

	public void setEfficiencyDate(java.lang.String efficiencyDate) {
		set("efficiency_date", efficiencyDate);
	}
	
	public java.lang.String getEfficiencyDate() {
		return getStr("efficiency_date");
	}

	public void setExpireDate(java.lang.String expireDate) {
		set("expire_date", expireDate);
	}
	
	public java.lang.String getExpireDate() {
		return getStr("expire_date");
	}

	public void setSourceId(java.lang.Integer sourceId) {
		set("source_id", sourceId);
	}
	
	public java.lang.Integer getSourceId() {
		return getInt("source_id");
	}

	public void setOnhand(java.lang.Integer onhand) {
		set("onhand", onhand);
	}
	
	public java.lang.Integer getOnhand() {
		return getInt("onhand");
	}

	public void setOnavailable(java.lang.Integer onavailable) {
		set("onavailable", onavailable);
	}
	
	public java.lang.Integer getOnavailable() {
		return getInt("onavailable");
	}

	public void setOnsend(java.lang.Integer onsend) {
		set("onsend", onsend);
	}
	
	public java.lang.Integer getOnsend() {
		return getInt("onsend");
	}

	public void setCteatetime(java.lang.String cteatetime) {
		set("cteatetime", cteatetime);
	}
	
	public java.lang.String getCteatetime() {
		return getStr("cteatetime");
	}

	public void setCreatedBy(java.lang.Integer createdBy) {
		set("created_by", createdBy);
	}
	
	public java.lang.Integer getCreatedBy() {
		return getInt("created_by");
	}

	public void setModifytime(java.lang.String modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.lang.String getModifytime() {
		return getStr("modifytime");
	}

	public void setModifyBy(java.lang.Integer modifyBy) {
		set("modify_by", modifyBy);
	}
	
	public java.lang.Integer getModifyBy() {
		return getInt("modify_by");
	}

}
