package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolepermission<M extends BaseRolepermission<M>> extends Model<M> implements IBean {

	public void setRoleid(java.lang.Integer roleid) {
		set("roleid", roleid);
	}
	
	public java.lang.Integer getRoleid() {
		return getInt("roleid");
	}

	public void setPermissioncode(java.lang.String permissioncode) {
		set("permissioncode", permissioncode);
	}
	
	public java.lang.String getPermissioncode() {
		return getStr("permissioncode");
	}

}
