package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCheckWorkAttendance<M extends BaseCheckWorkAttendance<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}
	
	public void setStartWorkTime(java.util.Date startWorkTime) {
		set("start_work_time", startWorkTime);
	}
	
	public java.util.Date getStartWorkTime() {
		return get("start_work_time");
	}
	
	public void setEndWorkTime(java.util.Date endWorkTime) {
		set("end_work_time", endWorkTime);
	}
	
	public java.util.Date getEndWorkTime() {
		return get("end_work_time");
	}
	
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}
	
}
