package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePhrase<M extends BasePhrase<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setNodeid(java.lang.Integer nodeid) {
		set("nodeid", nodeid);
	}
	
	public java.lang.Integer getNodeid() {
		return getInt("nodeid");
	}
	
	public void setPhraseName(java.lang.String phraseName) {
		set("phrase_name", phraseName);
	}
	
	public java.lang.String getPhraseName() {
		return getStr("phrase_name");
	}
	
	public void setPhraseContent(java.lang.String phraseContent) {
		set("phrase_content", phraseContent);
	}
	
	public java.lang.String getPhraseContent() {
		return getStr("phrase_content");
	}
	
	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.util.Date getModifytime() {
		return get("modifytime");
	}
	
}
