package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePatientRecycle<M extends BasePatientRecycle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPatientname(java.lang.String patientname) {
		set("patientname", patientname);
	}
	
	public java.lang.String getPatientname() {
		return getStr("patientname");
	}

	public void setPy(java.lang.String py) {
		set("py", py);
	}
	
	public java.lang.String getPy() {
		return getStr("py");
	}

	public void setPatientid(java.lang.String patientid) {
		set("patientid", patientid);
	}
	
	public java.lang.String getPatientid() {
		return getStr("patientid");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public void setBirthdate(java.lang.String birthdate) {
		set("birthdate", birthdate);
	}
	
	public java.lang.String getBirthdate() {
		return getStr("birthdate");
	}

	public void setHeight(java.math.BigDecimal height) {
		set("height", height);
	}
	
	public java.math.BigDecimal getHeight() {
		return get("height");
	}

	public void setWeight(java.math.BigDecimal weight) {
		set("weight", weight);
	}
	
	public java.math.BigDecimal getWeight() {
		return get("weight");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setPatientremark(java.lang.String patientremark) {
		set("patientremark", patientremark);
	}
	
	public java.lang.String getPatientremark() {
		return getStr("patientremark");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.util.Date getModifytime() {
		return get("modifytime");
	}
	
	public void setPatientidfk(java.lang.Integer patientidfk) {
		set("patientidfk", patientidfk);
	}
	
	public java.lang.Integer getPatientidfk() {
		return getInt("patientidfk");
	}
	
	public void setAdmissionidfk(java.lang.String admissionidfk) {
		set("admissionidfk", admissionidfk);
	}
	
	public java.lang.String getAdmissionidfk() {
		return getStr("admissionidfk");
	}
	
	public void setStudyorderidfk(java.lang.String studyorderidfk) {
		set("studyorderidfk", studyorderidfk);
	}
	
	public java.lang.String getStudyorderidfk() {
		return getStr("studyorderidfk");
	}

}
