package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSrcomponentoption<M extends BaseSrcomponentoption<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}
	
	public void setComponentUid(java.lang.String componentuid) {
		set("component_uid", componentuid);
	}
	
	public java.lang.String getComponentUid() {
		return getStr("component_uid");
	}

	public void setComponentId(java.lang.Integer componentId) {
		set("component_id", componentId);
	}
	
	public java.lang.Integer getComponentId() {
		return getInt("component_id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	public java.lang.String getValue() {
		return getStr("value");
	}
	
	public void setDisplayname(java.lang.String displayname) {
		set("displayname", displayname);
	}
	
	public java.lang.String getDisplayname() {
		return getStr("displayname");
	}

	public void setStandardCode(java.lang.String standardCode) {
		set("standard_code", standardCode);
	}
	
	public java.lang.String getStandardCode() {
		return getStr("standard_code");
	}
	
	public void setOpindex(java.lang.Integer opindex) {
		set("opindex", opindex);
	}
	
	public java.lang.Integer getOpindex() {
		return getInt("opindex");
	}
	
	public void setSectionuid(java.lang.String sectionuid) {
		set("sectionuid", sectionuid);
	}
	
	public java.lang.String getSectionuid() {
		return getStr("sectionuid");
	}

	public void setDefaultoption(java.lang.String defaultoption) {
		set("defaultoption", defaultoption);
	}
	
	public java.lang.String getDefaultoption() {
		return getStr("defaultoption");
	}
	
	public void setMutex(java.lang.String mutex) {
		set("mutex", mutex);
	}
	
	public java.lang.String getMutex() {
		return getStr("mutex");
	}
	
	public void setColor(java.lang.String color) {
		set("color", color);
	}
	
	public java.lang.String getColor() {
		return getStr("color");
	}
}
