package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeptShiftWorktime<M extends BaseDeptShiftWorktime<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setShiftid(java.lang.Integer shiftid) {
		set("shiftid", shiftid);
	}
	
	public java.lang.Integer getShiftid() {
		return getInt("shiftid");
	}

	public void setWorktimeid(java.lang.Integer worktimeid) {
		set("worktimeid", worktimeid);
	}
	
	public java.lang.Integer getWorktimeid() {
		return getInt("worktimeid");
	}

}
