package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSrsection<M extends BaseSrsection<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setDisplayname(java.lang.String displayname) {
		set("displayname", displayname);
	}
	
	public java.lang.String getDisplayname() {
		return getStr("displayname");
	}

	public void setSectioncontent(java.lang.String sectioncontent) {
		set("sectioncontent", sectioncontent);
	}
	
	public java.lang.String getSectioncontent() {
		return getStr("sectioncontent");
	}

	public void setIsQc(java.lang.Integer is_qc) {
		set("is_qc", is_qc);
	}
	
	public java.lang.Integer getIsQc() {
		return getInt("is_qc");
	}
	
	public void setClone(java.lang.Integer clone) {
		set("clone", clone);
	}
	
	public java.lang.Integer getClone() {
		return getInt("clone");
	}
	
	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

	public void setCreatorname(java.lang.String creatorname) {
		set("creatorname", creatorname);
	}
	
	public java.lang.String getCreatorname() {
		return getStr("creatorname");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setCatalog(java.lang.Integer catalog) {
		set("catalog", catalog);
	}
	
	public java.lang.Integer getCatalog() {
		return getInt("catalog");
	}
	
	public void setHeader(java.lang.Integer header) {
		set("header", header);
	}
	
	public java.lang.Integer getHeader() {
		return getInt("header");
	}
}
