package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNoticeRecord<M extends BaseNoticeRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setNoticeid(java.lang.Integer noticeid) {
		set("noticeid", noticeid);
	}
	
	public java.lang.Integer getNoticeid() {
		return getInt("noticeid");
	}

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public void setIsread(java.lang.Integer isread) {
		set("isread", isread);
	}
	
	public java.lang.Integer getIsread() {
		return getInt("isread");
	}

	public void setReminded(java.lang.Integer reminded) {
		set("reminded", reminded);
	}
	
	public java.lang.Integer getReminded() {
		return getInt("reminded");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
