package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChatMessageImg<M extends BaseChatMessageImg<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setImgpath(java.lang.String imgpath) {
		set("imgpath", imgpath);
	}
	
	public java.lang.String getImgpath() {
		return getStr("imgpath");
	}

}
