package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResearchForm<M extends BaseResearchForm<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setFormcontent(java.lang.String formcontent) {
		set("formcontent", formcontent);
	}
	
	public java.lang.String getFormcontent() {
		return getStr("formcontent");
	}
	
	public void setMaprule(java.lang.String maprule) {
		set("maprule", maprule);
	}
	
	public java.lang.String getMaprule() {
		return getStr("maprule");
	}
	
	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}
	
	public void setCreatorname(java.lang.String creatorname) {
		set("creatorname", creatorname);
	}
	
	public java.lang.String getCreatorname() {
		return getStr("creatorname");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
	public void setDatamodel(java.lang.String datamodel) {
		set("datamodel", datamodel);
	}
	
	public java.lang.String getDatamodel() {
		return getStr("datamodel");
	}
	
	public void setModelId(java.lang.Integer model_id) {
		set("model_id", model_id);
	}
	
	public java.lang.Integer getModelId() {
		return getInt("model_id");
	}
	
	public void setModelName(java.lang.String model_name) {
		set("model_name", model_name);
	}
	
	public java.lang.String getModelName() {
		return getStr("model_name");
	}
	
}
