package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUrgent<M extends BaseUrgent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setOrderid(java.lang.Integer orderid) {
		set("orderid", orderid);
	}
	
	public java.lang.Integer getOrderid() {
		return getInt("orderid");
	}
	
	public void setReportid(java.lang.Integer reportid) {
		set("reportid", reportid);
	}
	
	public java.lang.Integer getReportid() {
		return getInt("reportid");
	}
	
	public void setUrgentStatus(java.lang.String urgentStatus) {
		set("urgent_status", urgentStatus);
	}
	
	public java.lang.String getUrgentStatus() {
		return getStr("urgent_status");
	}
	
	public void setUrgentSubmitTxt(java.lang.String urgentSubmitTxt) {
		set("urgent_submit_txt", urgentSubmitTxt);
	}
	
	public java.lang.String getUrgentSubmitTxt() {
		return getStr("urgent_submit_txt");
	}
	
	public void setUrgentSubmitId(java.lang.Integer urgent_submit_id) {
		set("urgent_submit_id", urgent_submit_id);
	}
	
	public java.lang.Integer getUrgentSubmitId() {
		return getInt("urgent_submit_id");
	}
	
	public void setUrgentSubmitName(java.lang.String urgentSubmitName) {
		set("urgent_submit_name", urgentSubmitName);
	}
	
	public java.lang.String getUrgentSubmitName() {
		return getStr("urgent_submit_name");
	}
	
	public void setUrgentSubmitTime(java.util.Date urgentSubmitTime) {
		set("urgent_submit_time", urgentSubmitTime);
	}
	
	public java.util.Date getUrgentSubmitTime() {
		return get("urgent_submit_time");
	}
	
	public void setUrgentHandleCode(java.lang.String urgentHandleCode) {
		set("urgent_handle_code", urgentHandleCode);
	}
	
	public java.lang.String getUrgentHandleCode() {
		return getStr("urgent_handle_code");
	}
	
	public void setUrgentHandleTxt(java.lang.String urgentHandleTxt) {
		set("urgent_handle_txt", urgentHandleTxt);
	}
	
	public java.lang.String getUrgentHandleTxt() {
		return getStr("urgent_handle_txt");
	}
	
	public void setUrgentHandleName(java.lang.String urgentHandleName) {
		set("urgent_handle_name", urgentHandleName);
	}
	
	public java.lang.String getUrgentHandleName() {
		return getStr("urgent_handle_name");
	}
	
	public void setUrgentHandleTime(java.util.Date urgentHandleTime) {
		set("urgent_handle_time", urgentHandleTime);
	}
	
	public java.util.Date getUrgentHandleTime() {
		return get("urgent_handle_time");
	}
	
	public void setUrgentHandleDept(java.lang.String urgent_handle_dept) {
		set("urgent_handle_dept", urgent_handle_dept);
	}
	
	public java.lang.String getUrgentHandleDept() {
		return get("urgent_handle_dept");
	}
	
	public void setBarCodeNo(java.lang.String bar_code_no) {
		set("bar_code_no", bar_code_no);
	}
	
	public java.lang.String getBarCodeNo() {
		return get("bar_code_no");
	}
	
	public void setWardno(java.lang.String wardno) {
		set("wardno", wardno);
	}
	
	public java.lang.String getWardno() {
		return get("wardno");
	}
	
	public void setWorkAddress(java.lang.String work_address) {
		set("work_address", work_address);
	}
	
	public java.lang.String getWorkAddress() {
		return get("work_address");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.util.Date getModifytime() {
		return get("modifytime");
	}
	
}
