package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserDac<M extends BaseUserDac<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}
	
	public void setUserid(Integer userid) {
		set("userid", userid);
	}
	
	public Integer getUserid() {
		return getInt("userid");
	}
	
	public void setInstitutionIds(String institutionIds) {
		set("institution_ids", institutionIds);
	}
	
	public String getInstitutionIds() {
		return getStr("institution_ids");
	}
	
	public void setDeptIds(String deptIds) {
		set("dept_ids", deptIds);
	}
	
	public String getDeptIds() {
		return getStr("dept_ids");
	}
	
	public void setModIds(String modIds) {
		set("mod_ids", modIds);
	}
	
	public String getModIds() {
		return getStr("mod_ids");
	}
	
}
