package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;


import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChatApplyFriend<M extends BaseChatApplyFriend<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setFromid(java.lang.Integer fromid) {
		set("fromid", fromid);
	}
	
	public java.lang.Integer getFromid() {
		return getInt("fromid");
	}

	public void setToid(java.lang.Integer toid) {
		set("toid", toid);
	}
	
	public java.lang.Integer getToid() {
		return getInt("toid");
	}

	public void setGroupid(java.lang.Integer groupid) {
		set("groupid", groupid);
	}
	
	public java.lang.Integer getGroupid() {
		return getInt("groupid");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setHandelresult(java.lang.Integer handelresult) {
		set("handelresult", handelresult);
	}
	
	public java.lang.Integer getHandelresult() {
		return getInt("handelresult");
	}

	public void setHandeltime(java.util.Date handeltime) {
		set("handeltime", handeltime);
	}
	
	public java.util.Date getHandeltime() {
		return get("handeltime");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
