package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResearchRoleAuthority<M extends BaseResearchRoleAuthority<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}
	
	public java.lang.Integer getRoleId() {
		return getInt("role_id");
	}
	
	public void setAuthorityId(java.lang.Integer authorityId) {
		set("authority_id", authorityId);
	}
	
	public java.lang.Integer getAuthorityId() {
		return getInt("authority_id");
	}
	
}
