package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEorderitem<M extends BaseEorderitem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setEorderfk(java.lang.Integer eorderfk) {
		set("eorderfk", eorderfk);
	}
	
	public java.lang.Integer getEorderfk() {
		return getInt("eorderfk");
	}
	
	public void setItemid(java.lang.String itemid) {
		set("itemid", itemid);
	}
	
	public java.lang.String getItemid() {
		return getStr("itemid");
	}
	
	public void setModality(java.lang.String modality) {
		set("modality", modality);
	}
	
	public java.lang.String getModality() {
		return getStr("modality");
	}
	
	public void setItemCode(java.lang.String itemCode) {
		set("item_code", itemCode);
	}
	
	public java.lang.String getItemCode() {
		return getStr("item_code");
	}
	
	public void setItemName(java.lang.String itemName) {
		set("item_name", itemName);
	}
	
	public java.lang.String getItemName() {
		return getStr("item_name");
	}
	
	public void setOrganCode(java.lang.String organCode) {
		set("organ_code", organCode);
	}
	
	public java.lang.String getOrganCode() {
		return getStr("organ_code");
	}
	
	public void setOrgan(java.lang.String organ) {
		set("organ", organ);
	}
	
	public java.lang.String getOrgan() {
		return getStr("organ");
	}
	
	public void setSuborganCode(java.lang.String suborganCode) {
		set("suborgan_code", suborganCode);
	}
	
	public java.lang.String getSuborganCode() {
		return getStr("suborgan_code");
	}
	
	public void setSuborgan(java.lang.String suborgan) {
		set("suborgan", suborgan);
	}
	
	public java.lang.String getSuborgan() {
		return getStr("suborgan");
	}
	
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}
	
	public void setRealprice(java.math.BigDecimal realprice) {
		set("realprice", realprice);
	}
	
	public java.math.BigDecimal getRealprice() {
		return get("realprice");
	}
	
	public void setChargeStatus(java.lang.String chargeStatus) {
		set("charge_status", chargeStatus);
	}
	
	public java.lang.String getChargeStatus() {
		return getStr("charge_status");
	}
	
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}
	
}
