package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicCalling<M extends BaseDicCalling<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setModalityid(java.lang.Integer modalityid) {
		set("modalityid", modalityid);
	}
	
	public java.lang.Integer getModalityid() {
		return getInt("modalityid");
	}

	public void setPriority(java.lang.Integer priority) {
		set("priority", priority);
	}
	
	public java.lang.Integer getPriority() {
		return getInt("priority");
	}

	public void setMessage(java.lang.String message) {
		set("message", message);
	}
	
	public java.lang.String getMessage() {
		return getStr("message");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
