package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudyprocess<M extends BaseStudyprocess<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setPatientfk(java.lang.Integer patientfk) {
		set("patientfk", patientfk);
	}
	
	public java.lang.Integer getPatientfk() {
		return getInt("patientfk");
	}
	
	public void setAdmissionfk(java.lang.Integer admissionfk) {
		set("admissionfk", admissionfk);
	}
	
	public java.lang.Integer getAdmissionfk() {
		return getInt("admissionfk");
	}
	
	public void setStudyorderfk(java.lang.Integer studyorderfk) {
		set("studyorderfk", studyorderfk);
	}
	
	public java.lang.Integer getStudyorderfk() {
		return getInt("studyorderfk");
	}
	
	public void setReportfk(java.lang.Integer reportfk) {
		set("reportfk", reportfk);
	}
	
	public java.lang.Integer getReportfk() {
		return getInt("reportfk");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}
	
	public java.lang.String getOperator() {
		return getStr("operator");
	}
	
	public void setOperatorname(java.lang.String operatorname) {
		set("operatorname", operatorname);
	}
	
	public java.lang.String getOperatorname() {
		return getStr("operatorname");
	}
	
	public void setOperatetime(java.util.Date operatetime) {
		set("operatetime", operatetime);
	}
	
	public java.util.Date getOperatetime() {
		return get("operatetime");
	}
	
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	public void setLogmessages(java.lang.String logmessages) {
		set("logmessages", logmessages);
	}
	
	public java.lang.String getLogmessages() {
		return getStr("logmessages");
	}
	
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}
	
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}
	
}
