package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicEquipGroup<M extends BaseDicEquipGroup<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setGpname(java.lang.String gpname) {
		set("gpname", gpname);
	}
	
	public java.lang.String getGpname() {
		return getStr("gpname");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setDefaultDuration(java.lang.String defaultDuration) {
		set("default_duration", defaultDuration);
	}
	
	public java.lang.String getDefaultDuration() {
		return getStr("default_duration");
	}
	
	public void setDeleted(java.lang.String deleted) {
		set("deleted", deleted);
	}

	public java.lang.String getDeleted() {
		return get("deleted");
	}

}
