package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmergencyDefaultInfo<M extends BaseEmergencyDefaultInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setConfigname(java.lang.String configname) {
		set("configname", configname);
	}
	
	public java.lang.String getConfigname() {
		return getStr("configname");
	}

	public void setPatientname(java.lang.String patientname) {
		set("patientname", patientname);
	}
	
	public java.lang.String getPatientname() {
		return getStr("patientname");
	}

	public void setPy(java.lang.String py) {
		set("py", py);
	}
	
	public java.lang.String getPy() {
		return getStr("py");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public void setBirthdate(java.lang.String birthdate) {
		set("birthdate", birthdate);
	}
	
	public java.lang.String getBirthdate() {
		return getStr("birthdate");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public void setAgeunit(java.lang.String ageunit) {
		set("ageunit", ageunit);
	}
	
	public java.lang.String getAgeunit() {
		return getStr("ageunit");
	}

	public void setPatientsource(java.lang.String patientsource) {
		set("patientsource", patientsource);
	}
	
	public java.lang.String getPatientsource() {
		return getStr("patientsource");
	}

	public void setModalityid(java.lang.Integer modalityid) {
		set("modalityid", modalityid);
	}
	
	public java.lang.Integer getModalityid() {
		return getInt("modalityid");
	}

	public void setModalityType(java.lang.String modalityType) {
		set("modality_type", modalityType);
	}
	
	public java.lang.String getModalityType() {
		return getStr("modality_type");
	}

	public void setStudyitemName(java.lang.String studyitemName) {
		set("studyitem_name", studyitemName);
	}
	
	public java.lang.String getStudyitemName() {
		return getStr("studyitem_name");
	}

	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.util.Date getModifytime() {
		return get("modifytime");
	}

}
