package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReportremark<M extends BaseReportremark<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPatientidfk(java.lang.Integer patientidfk) {
		set("patientidfk", patientidfk);
	}
	
	public java.lang.Integer getPatientidfk() {
		return getInt("patientidfk");
	}

	public void setAdmissionidfk(java.lang.Integer admissionidfk) {
		set("admissionidfk", admissionidfk);
	}
	
	public java.lang.Integer getAdmissionidfk() {
		return getInt("admissionidfk");
	}
	
	public void setOrderid(java.lang.Integer orderid) {
		set("admissionidfk", orderid);
	}
	
	public java.lang.Integer getOrderid() {
		return getInt("orderid");
	}

	public void setStudyid(java.lang.String studyid) {
		set("studyid", studyid);
	}
	
	public java.lang.String getStudyid() {
		return getStr("studyid");
	}

	public void setRemarkcontent(java.lang.String remarkcontent) {
		set("remarkcontent", remarkcontent);
	}
	
	public java.lang.String getRemarkcontent() {
		return getStr("remarkcontent");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public void setModifytime(java.util.Date modifytime) {
		set("modifytime", modifytime);
	}
	
	public java.util.Date getModifytime() {
		return get("modifytime");
	}

}
