package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrinter<M extends BasePrinter<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPrintername(java.lang.String printername) {
		set("printername", printername);
	}
	
	public java.lang.String getPrintername() {
		return getStr("printername");
	}

	public void setHostip(java.lang.String hostip) {
		set("hostip", hostip);
	}
	
	public java.lang.String getHostip() {
		return getStr("hostip");
	}

	public void setHostname(java.lang.String hostname) {
		set("hostname", hostname);
	}
	
	public java.lang.String getHostname() {
		return getStr("hostname");
	}
	
	public void setPrinterdescription(java.lang.String printerdescription) {
        set("printerdescription", printerdescription);
    }
    
    public java.lang.String getPrinterdescription() {
        return getStr("printerdescription");
    }
    
    public void setTemplatename(java.lang.String templatename) {
        set("templatename", templatename);
    }
    
    public java.lang.String getTemplatename() {
        return getStr("templatename");
    }
    
    public void setTemplatedescription(java.lang.String templatedescription) {
        set("templatedescription", templatedescription);
    }
    
    public java.lang.String getTemplatedescription() {
        return getStr("templatedescription");
    }
    
    public void setTemplatetype(java.lang.Integer templatetype) {
		set("templatetype", templatetype);
	}
	
	public java.lang.Integer getTemplatetype() {
		return getInt("templatetype");
	}

}
