package com.healta.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStatisticalcustomconditions<M extends BaseStatisticalcustomconditions<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStatisticalreportfk(java.lang.Integer statisticalreportfk) {
		set("statisticalreportfk", statisticalreportfk);
	}
	
	public java.lang.Integer getStatisticalreportfk() {
		return getInt("statisticalreportfk");
	}

	public void setLabel(java.lang.String label) {
		set("label", label);
	}
	
	public java.lang.String getLabel() {
		return getStr("label");
	}

	public void setColumnname(java.lang.String columnname) {
		set("columnname", columnname);
	}
	
	public java.lang.String getColumnname() {
		return getStr("columnname");
	}

	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}
	
	public java.lang.String getOperator() {
		return getStr("operator");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

}
