package com.healta.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit2 {
	
	public static void mapping(ActiveRecordPlugin arp) {
            arp.addMapping("user_audit_logs", "id", UserAuditLogs.class);
            arp.addMapping("authority", "id", Authority.class);
            arp.addMapping("dic_examitem", "id", DicExamitem.class);
            arp.addMapping("id1", "id", Id1.class);
            arp.addMapping("id2", "id", Id2.class);
            arp.addMapping("id3", "id", Id3.class);
            arp.addMapping("dic_modality", "id", DicModality.class);
            arp.addMapping("patient", "id", Patient.class);
            arp.addMapping("report", "id", Report.class);
            arp.addMapping("reporttemplate", "id", Reporttemplate.class);
            arp.addMapping("reporttemplatenode", "id", Reporttemplatenode.class);
            arp.addMapping("role", "id", Role.class);
            arp.addMapping("studyitem", "id", Studyitem.class);
            arp.addMapping("studyorder", "id", Studyorder.class);
            arp.addMapping("syscode", "id", Syscode.class);
            arp.addMapping("userrole", "roleid,userid", Userrole.class);
            arp.addMapping("users", "id", User.class);
            arp.addMapping("user_dac", "id", UserDac.class);
            arp.addMapping("resource", "id", Resource.class);
            arp.addMapping("authority_resource", "id", AuthorityResource.class);
            arp.addMapping("role_authority", "id", RoleAuthority.class);
            arp.addMapping("clinicalcode", "id", ClinicalCode.class);
            arp.addMapping("filter", "id", Filter.class);
            arp.addMapping("srcomponent", "id", SRComponent.class);
            arp.addMapping("srtemplate", "id", SRTemplate.class);
            arp.addMapping("xslttemplate", "id", Xslttemplate.class);
            arp.addMapping("syngoviareport", "id", Syngoviareport.class);
            arp.addMapping("syngoviaimage", "id", Syngoviaimage.class);
            arp.addMapping("reportrace", "id", Reportrace.class);
            arp.addMapping("structreport", "id", Structreport.class);
            arp.addMapping("dic_regex", "id", DicRegex.class);
            arp.addMapping("syngoviasrdata", "id", Syngoviasrdata.class);
            arp.addMapping("syngoviafindingfile", "id", Syngoviafindingfile.class);
            arp.addMapping("synctime", "id", Synctime.class);
            arp.addMapping("favorites", "id", Favorites.class);
            arp.addMapping("favoritesreport", "id", Favoritesreport.class);
            arp.addMapping("srcomponentoption", "id", Srcomponentoption.class);
            arp.addMapping("modules", "id", Modules.class);
            arp.addMapping("role_module", "id", RoleModule.class);
            arp.addMapping("userprofiles", "id", UserProfiles.class);
            arp.addMapping("statisticalreport", "id", Statisticalreport.class);
            arp.addMapping("ae", "id", Ae.class);
            arp.addMapping("mwlitem", "id", Mwlitem.class);
            arp.addMapping("admission", "id", Admission.class);
            arp.addMapping("dic_organ", "id", DicOrgan.class);
            arp.addMapping("eorder", "id", Eorder.class);
            arp.addMapping("eorderitem", "id", Eorderitem.class);
            arp.addMapping("dic_equip_group", "id", DicEquipGroup.class);
            arp.addMapping("dic_exam_equip", "id", DicExamEquip.class);
            arp.addMapping("reportremark", "id", Reportremark.class);
            arp.addMapping("label", "id", Label.class);
            arp.addMapping("labelfolder", "id", Labelfolder.class);
            arp.addMapping("reportlabel", "id", Reportlabel.class);
            arp.addMapping("study", "id", Study.class);
            arp.addMapping("srsection", "id", Srsection.class);
            arp.addMapping("status_color", "id", StatusColor.class);
            arp.addMapping("dic_department", "id", DicDepartment.class);
            arp.addMapping("dic_employee", "id", DicEmployee.class);
            arp.addMapping("studyorder_number", "id", StudyorderNumber.class);
            arp.addMapping("client", "id", Client.class);
            arp.addMapping("printer", "id", Printer.class);
            arp.addMapping("study_image", "id", StudyImage.class);
            arp.addMapping("studyprocess", "id", Studyprocess.class);
            arp.addMapping("statisticalclassify", "id", Statisticalclassify.class);
            arp.addMapping("statisticalcustomconditions", "id", Statisticalcustomconditions.class);
            arp.addMapping("chat_message", "id", ChatMessage.class);
            arp.addMapping("chat_group", "id", ChatGroup.class);
            arp.addMapping("chat_message_img", "id", ChatMessageImg.class);
            arp.addMapping("chat_group_user", "id", ChatGroupUser.class);
            arp.addMapping("chat_group_msg", "id", ChatGroupMsg.class);
            arp.addMapping("dic_institution", "id", DicInstitution.class);
            arp.addMapping("patient_recycle", "id", PatientRecycle.class);
            arp.addMapping("dic_institution_role", "id", DicInstitutionRole.class);
            arp.addMapping("chat_friendlist", "id", ChatFriendlist.class);
            arp.addMapping("chat_apply_friend", "id", ChatApplyFriend.class);
            arp.addMapping("ris_trigger", "id", RisTrigger.class);
            arp.addMapping("quicksearch", "id", Quicksearch.class);
            arp.addMapping("dic_icd_node", "id", DicIcdNode.class);
            arp.addMapping("dic_icd10", "id", DicIcd10.class);
            arp.addMapping("reporticd", "id", Reporticd.class);
            arp.addMapping("dept_worktime", "id", DeptWorktime.class);
            arp.addMapping("dept_shift", "id", DeptShift.class);
            arp.addMapping("dept_shift_worktime", "id", DeptShiftWorktime.class);
            arp.addMapping("dept_post_shift", "id", DeptPostShift.class);
            arp.addMapping("printtemplate", "id", Printtemplate.class);
            arp.addMapping("user_shortcut_config", "id", UserShortcutConfig.class);
            arp.addMapping("emergency_default_info", "id", EmergencyDefaultInfo.class);
            arp.addMapping("emergency_studyitem", "id", EmergencyStudyitem.class);
            arp.addMapping("unmatchstudy", "id", Unmatchstudy.class);
            arp.addMapping("study_method_template", "id", StudyMethodTemplate.class);
            arp.addMapping("retrialviewlist", "id", Retrialviewlist.class);
            arp.addMapping("rejectopinion", "id", Rejectopinion.class);
            arp.addMapping("notice", "id", Notice.class);
            arp.addMapping("notice_record", "id", NoticeRecord.class);
            arp.addMapping("dept_shift_work", "id", DeptShiftWork.class);
            arp.addMapping("study_material_default", "id", StudyMaterialDefault.class);
            arp.addMapping("dept_report_task_setting", "id", DeptReportTaskSetting.class);
            arp.addMapping("dept_subscription_rule", "id", DeptSubscriptionRule.class);
            arp.addMapping("dept_subscription_modality", "id", DeptSubscriptionModality.class);
            arp.addMapping("dept_subscription_examitem", "id", DeptSubscriptionExamitem.class);
            arp.addMapping("com_goods", "id", ComGoods.class);
            arp.addMapping("com_goods_variety", "id", ComGoodsVariety.class);

            arp.addMapping("previous_history", "id", PreviousHistory.class);
            arp.addMapping("inquiry", "id", Inquiry.class);
            arp.addMapping("injection", "id", Injection.class);
            arp.addMapping("purchase_order", "id", PurchaseOrder.class);
            arp.addMapping("purchase_order_lines", "id", PurchaseOrderLines.class);
            arp.addMapping("stock", "id", Stock.class);
            arp.addMapping("ssc_sale_order", "id", SscSaleOrder.class);
            arp.addMapping("ssc_sale_order_lines", "id", SscSaleOrderLines.class);
            arp.addMapping("dic_calling", "id", DicCalling.class);
            arp.addMapping("dic_reportcorrect_rules", "id", DicReportcorrectRules.class);
            arp.addMapping("patientcallingrecord", "id", Patientcallingrecord.class);
            arp.addMapping("check_work_attendance", "id", CheckWorkAttendance.class);
            arp.addMapping("followup", "id", Followup.class);
            arp.addMapping("password_policy", "id", PasswordPolicy.class);
            arp.addMapping("phrase_node", "id", PhraseNode.class);
            arp.addMapping("phrase", "id", Phrase.class);
            arp.addMapping("modality_record", "id", ModalityRecord.class);
            arp.addMapping("urgent", "id", Urgent.class);
            arp.addMapping("study_acquisition_mode_default", "id", StudyAcquisitionModeDefault.class);
            arp.addMapping("dic_common", "id", DicCommon.class);

            arp.addMapping("research_project", "id", ResearchProject.class);
            arp.addMapping("research_test_group", "id", ResearchTestGroup.class);
            arp.addMapping("research_testgroup_data", "id", ResearchTestgroupData.class);
            arp.addMapping("research_user_role", "id", ResearchUserRole.class);
            arp.addMapping("research_role", "id", ResearchRole.class);
            arp.addMapping("research_form", "id", ResearchForm.class);
            arp.addMapping("research_form_data", "id", ResearchFormData.class);
            arp.addMapping("research_joingroup_apply", "id", ResearchJoingroupApply.class);
            arp.addMapping("research_joingroup_rule", "id", ResearchJoingroupRule.class);
            arp.addMapping("research_testgroup_form", "id", ResearchTestgroupForm.class);
            arp.addMapping("research_joingroup_apply_items", "id", ResearchJoingroupApplyItems.class);
            arp.addMapping("research_joingroup_rule_item", "id", ResearchJoingroupRuleItem.class);
            arp.addMapping("research_authority", "id", ResearchAuthority.class);
            arp.addMapping("research_role_authority", "id", ResearchRoleAuthority.class);
            arp.addMapping("research_resource", "id", ResearchResource.class);
            arp.addMapping("research_authority_resource", "id", ResearchAuthorityResource.class);
    	arp.addMapping("research_id1", "id", ResearchId1.class);
	}
}

