package com.healta.model;

import com.healta.model.base.BaseAe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ae extends BaseAe<Ae> {
	public static final Ae dao = new Ae().dao();
	
	public Ae getAeByAET(String aet){
		return dao.findFirst("select * from ae where aet=?",aet);
	}
	
}
