package com.healta.model;

import com.healta.model.base.BaseAuthority;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Authority extends BaseAuthority<Authority> {
	public static final Authority dao = new Authority().dao();
	
	
	public Authority findAuthorityByName(String name){
		return Authority.dao.findFirst("select * from authority where name='"+name+"'");
	}
}
