package com.healta.model;

import com.healta.model.base.BaseAuthorityResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthorityResource extends BaseAuthorityResource<AuthorityResource> {
	public static final AuthorityResource dao = new AuthorityResource().dao();
}
