package com.healta.model;

import com.healta.model.base.BaseChatGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatGroup extends BaseChatGroup<ChatGroup> {
	public static final ChatGroup dao = new ChatGroup().dao();
}
