package com.healta.model;

import com.healta.model.base.BaseChatGroupUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatGroupUser extends BaseChatGroupUser<ChatGroupUser> {
	public static final ChatGroupUser dao = new ChatGroupUser().dao();
}
