package com.healta.model;

import com.healta.model.base.BaseChatFriendlist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatFriendlist extends BaseChatFriendlist<ChatFriendlist> {
	public static final ChatFriendlist dao = new ChatFriendlist().dao();
}
