package com.healta.model;

import com.healta.model.base.BaseChatGroupMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatGroupMsg extends BaseChatGroupMsg<ChatGroupMsg> {
	public static final ChatGroupMsg dao = new ChatGroupMsg().dao();
}
