package com.healta.model;

import com.healta.model.base.BaseChatApplyFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatApplyFriend extends BaseChatApplyFriend<ChatApplyFriend> {
	public static final ChatApplyFriend dao = new ChatApplyFriend().dao();
}
