package com.healta.model;

import com.healta.model.base.BaseChatMessageImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatMessageImg extends BaseChatMessageImg<ChatMessageImg> {
	public static final ChatMessageImg dao = new ChatMessageImg().dao();
}
