package com.healta.model;

import java.util.Date;
import java.util.List;

import org.apache.commons.lang.StringUtils;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.healta.constant.ChatMessageType;
import com.healta.model.base.BaseChatMessage;
import com.healta.util.WebSocketUtils;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;

import sun.util.logging.resources.logging;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatMessage extends BaseChatMessage<ChatMessage> {
	public static final ChatMessage dao = new ChatMessage().dao();
	
	public JSONObject toJsonObj(Boolean mine){
		JSONObject json=new JSONObject();
		json.put("cid", this.getId());
		User user=User.dao.findById(this.getFromid());
		json.put("username", user.getName());
		json.put("avatar", user.getAvatar());
		
		if(StrKit.equals(ChatMessageType.FRIEND, this.getSourcetype())){
			json.put("id", this.getFromid());
		}
		if(StrKit.equals(ChatMessageType.GROUP, this.getSourcetype())){
			json.put("id", this.getToid());
//			ChatGroup cg=ChatGroup.dao.findById(this.getToid());
//			json.put("username", cg.getGroupname());
//			json.put("avatar", StrKit.isBlank(cg.getAvatar())?"themes/head.ico":cg.getAvatar());
		}
		
		
		json.put("type", this.getSourcetype());
		if(this.getMsgtype()==1){
			json.put("content", "img[image/getChatImg?id=" + this.getMsgcontent() + "]");//image/getChatImg?id=22
		}
		else{
			json.put("content", this.getMsgcontent());
		}
		
		json.put("mine", mine);
		json.put("fromid", this.getFromid());
		json.put("timestamp", this.getCreatetime().getTime());
		return json;
	}
	
	public ChatMessage createByJsonObj(JSONObject obj){
		ChatMessage ret=new ChatMessage();
		JSONObject mine=obj.getJSONObject("mine");
    	JSONObject to=obj.getJSONObject("to");
		ret.setFromid(mine.getInteger("id"));
		ret.setToid(to.getInteger("id"));
		String type=to.getString("type");
//		if(StrKit.equals(ChatMessageType.FRIEND, type)){
//			ret.setIsoffline(WebSocketUtils.isOnline(to.getInteger("id"))?1:0);
//		}
		ret.setSourcetype(type);
		if(StringUtils.startsWith(mine.getString("content"), "img[")){
			
			System.out.println(mine.getString("content")+"-----"+StringUtils.substringBetween(mine.getString("content"), "img[image/getChatImg?id=", "]"));
			
			ret.setMsgcontent(StringUtils.substringBetween(mine.getString("content"), "img[image/getChatImg?id=", "]"));
			ret.setMsgtype(ChatMessageType.CONTENTTYPE_IMG);
		}
		else{
			ret.setMsgcontent(mine.getString("content"));
			ret.setMsgtype(ChatMessageType.CONTENTTYPE_STRING);
		}
		ret.setCreatetime(new Date());
		return ret;
	}

}
