package com.healta.model;

import com.healta.model.base.BaseCheckWorkAttendance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CheckWorkAttendance extends BaseCheckWorkAttendance<CheckWorkAttendance> {
	public static final CheckWorkAttendance dao = new CheckWorkAttendance().dao();
}
