package com.healta.model;

import com.healta.model.base.BaseClient;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Client extends BaseClient<Client> {
	public static final Client dao = new Client().dao();
	
	public Client findByHostip(String hostip) {
		return Client.dao.findFirst("SELECT TOP 1 * FROM client WHERE hostip = ?", hostip);
	}
}
