package com.healta.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.healta.model.base.BaseComGoods;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ComGoods extends BaseComGoods<ComGoods> {
	public static final ComGoods dao = new ComGoods().dao();
	
	/**
	 * 保存商品信息
	 * @param comgoods  商品对象
	 * @return
	 */
	public boolean saveComGoods(ComGoods comgoods) {
		return comgoods.remove("id").save();
	}
    
	/**
	 * 修改商品信息
	 * @param comgoods  商品对象
	 * @return
	 */
	public boolean updateComGoods(ComGoods comgoods) {
		return comgoods.update();
	}
	/**
	 * 根据条件查询商品信息
	 * @param map
	 * @return
	 */
	public List<ComGoods> findComGoods(Map<String, String[]> map) {
		StringBuffer sb=new StringBuffer();
		List<Object> list=new ArrayList<Object>();
		sb.append("select * from com_goods cg where deleted=0");
		if(StrKit.notBlank(map.get("comGoodsId")) && StrKit.notBlank(map.get("comGoodsId")[0])) {
			sb.append(" and cg.id LIKE CONCAT('%',?,'%')");
			list.add(map.get("comGoodsId")[0]);
		}
		if(StrKit.notBlank(map.get("comGoodsName")) && StrKit.notBlank(map.get("comGoodsName")[0])) {
			sb.append(" and cg.goods_name LIKE CONCAT('%',?,'%')");
			list.add(map.get("comGoodsName")[0]);
		}
		if(StrKit.notBlank(map.get("comGoodsVariety")) && StrKit.notBlank(map.get("comGoodsVariety")[0])) {
			sb.append(" and cg.com_goods_variety_id=?'");
			list.add(map.get("comGoodsVariety")[0]);
		}
		if(StrKit.notBlank(map.get("comLot")) && StrKit.notBlank(map.get("comLot")[0])) {
			sb.append(" and cg.com_lot=?");
			list.add(map.get("comLot")[0]);
		}
		if(StrKit.notBlank(map.get("productLocation")) && StrKit.notBlank(map.get("productLocation")[0])) {
			sb.append(" and cg.product_location=?");
			list.add(map.get("productLocation")[0]);
		}
		return dao.find(sb.toString(),list.toArray());
	}

	public boolean deleteComGoods(Integer id) {
		StringBuffer sb=new StringBuffer();
		sb.append("update com_goods set deleted=1 where id="+id);
		int i=Db.update(sb.toString());
		if(i==1) {
			return true;
		}
		return false;
	}
	
}
