package com.healta.model;

import com.healta.model.base.BaseDeptShift;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeptShift extends BaseDeptShift<DeptShift> {
	public static final DeptShift dao = new DeptShift().dao();
}
