package com.healta.model;

import com.healta.model.base.BaseDeptReportTaskSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeptReportTaskSetting extends BaseDeptReportTaskSetting<DeptReportTaskSetting> {
	public static final DeptReportTaskSetting dao = new DeptReportTaskSetting().dao();
}
