package com.healta.model;

import com.healta.model.base.BaseDeptSubscriptionModality;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeptSubscriptionModality extends BaseDeptSubscriptionModality<DeptSubscriptionModality> {
	public static final DeptSubscriptionModality dao = new DeptSubscriptionModality().dao();
}
