package com.healta.model;

import com.healta.model.base.BaseDeptPostShift;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeptPostShift extends BaseDeptPostShift<DeptPostShift> {
	public static final DeptPostShift dao = new DeptPostShift().dao();
}
