package com.healta.model;

import com.healta.model.base.BaseDeptSubscriptionRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeptSubscriptionRule extends BaseDeptSubscriptionRule<DeptSubscriptionRule> {
	public static final DeptSubscriptionRule dao = new DeptSubscriptionRule().dao();
}
