package com.healta.model;

import com.healta.model.base.BaseDeptShiftWorktime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeptShiftWorktime extends BaseDeptShiftWorktime<DeptShiftWorktime> {
	public static final DeptShiftWorktime dao = new DeptShiftWorktime().dao();
}
