package com.healta.model;

import com.healta.model.base.BaseDeptWorktime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeptWorktime extends BaseDeptWorktime<DeptWorktime> {
	public static final DeptWorktime dao = new DeptWorktime().dao();
}
