package com.healta.model;

import com.healta.model.base.BaseDeptShiftWork;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeptShiftWork extends BaseDeptShiftWork<DeptShiftWork> {
	public static final DeptShiftWork dao = new DeptShiftWork().dao();
}
