package com.healta.model;

import com.healta.model.base.BaseDeptSubscriptionExamitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeptSubscriptionExamitem extends BaseDeptSubscriptionExamitem<DeptSubscriptionExamitem> {
	public static final DeptSubscriptionExamitem dao = new DeptSubscriptionExamitem().dao();
}
