package com.healta.model;

import com.healta.model.base.BaseDicCancelReason;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicCancelReason extends BaseDicCancelReason<DicCancelReason> {
	public static final DicCancelReason dao = new DicCancelReason().dao();
}
