package com.healta.model;

import com.healta.model.base.BaseDicCalling;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicCalling extends BaseDicCalling<DicCalling> {
	public static final DicCalling dao = new DicCalling().dao();
}
