package com.healta.model;

import com.healta.model.base.BaseDicDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicDepartment extends BaseDicDepartment<DicDepartment> {
	public static final DicDepartment dao = new DicDepartment().dao();
}
