package com.healta.model;

import com.healta.model.base.BaseDicEmployee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicEmployee extends BaseDicEmployee<DicEmployee> {
	public static final DicEmployee dao = new DicEmployee().dao();
}
