package com.healta.model;

import com.healta.model.base.BaseDicExamEquip;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicExamEquip extends BaseDicExamEquip<DicExamEquip> {
	public static final DicExamEquip dao = new DicExamEquip().dao();
}
