package com.healta.model;

import com.healta.model.base.BaseDicEquipGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicEquipGroup extends BaseDicEquipGroup<DicEquipGroup> {
	public static final DicEquipGroup dao = new DicEquipGroup().dao();
}
