package com.healta.model;

import com.healta.model.base.BaseDicExamitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicExamitem extends BaseDicExamitem<DicExamitem> {
	public static final DicExamitem dao = new DicExamitem().dao();
}
