package com.healta.model;

import com.healta.model.base.BaseDicInstitutionRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicInstitutionRole extends BaseDicInstitutionRole<DicInstitutionRole> {
	public static final DicInstitutionRole dao = new DicInstitutionRole().dao();
}
