package com.healta.model;

import com.healta.model.base.BaseDicIcdNode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicIcdNode extends BaseDicIcdNode<DicIcdNode> {
	public static final DicIcdNode dao = new DicIcdNode().dao();
}
