package com.healta.model;

import com.healta.model.base.BaseDicInstitution;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicInstitution extends BaseDicInstitution<DicInstitution> {
	public static final DicInstitution dao = new DicInstitution().dao();
}
