package com.healta.model;

import com.healta.model.base.BaseDicIcd10;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicIcd10 extends BaseDicIcd10<DicIcd10> {
	public static final DicIcd10 dao = new DicIcd10().dao();
}
