package com.healta.model;

import com.healta.model.base.BaseDicModality;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicModality extends BaseDicModality<DicModality> {
	public static final DicModality dao = new DicModality().dao();
}
