package com.healta.model;

import com.healta.model.base.BaseDicOrgan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicOrgan extends BaseDicOrgan<DicOrgan> {
	public static final DicOrgan dao = new DicOrgan().dao();
}
