package com.healta.model;

import com.healta.model.base.BaseDicRegex;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicRegex extends BaseDicRegex<DicRegex> {
	public static final DicRegex dao = new DicRegex().dao();
}
