package com.healta.model;

import com.healta.model.base.BaseDicReportcorrectRules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicReportcorrectRules extends BaseDicReportcorrectRules<DicReportcorrectRules> {
	public static final DicReportcorrectRules dao = new DicReportcorrectRules().dao();
}
