package com.healta.model;

import com.healta.model.base.BaseEmergencyStudyitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmergencyStudyitem extends BaseEmergencyStudyitem<EmergencyStudyitem> {
	public static final EmergencyStudyitem dao = new EmergencyStudyitem().dao();
}
