package com.healta.model;

import com.healta.model.base.BaseEmergencyDefaultInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmergencyDefaultInfo extends BaseEmergencyDefaultInfo<EmergencyDefaultInfo> {
	public static final EmergencyDefaultInfo dao = new EmergencyDefaultInfo().dao();
}
