package com.healta.model;

import com.healta.model.base.BaseEorderitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Eorderitem extends BaseEorderitem<Eorderitem> {
	public static final Eorderitem dao = new Eorderitem().dao();
}
