package com.healta.model;

import com.healta.model.base.BaseEorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Eorder extends BaseEorder<Eorder> {
	public static final Eorder dao = new Eorder().dao();
}
