package com.healta.model;

import com.healta.model.base.BaseFavorites;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Favorites extends BaseFavorites<Favorites> {
	public static final Favorites dao = new Favorites().dao();
}
