package com.healta.model;

import com.healta.model.base.BaseFavoritesreport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Favoritesreport extends BaseFavoritesreport<Favoritesreport> {
	public static final Favoritesreport dao = new Favoritesreport().dao();
}
