package com.healta.model;

import java.util.Set;

import com.healta.model.base.BaseFilter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Filter extends BaseFilter<Filter> {
	public static final Filter dao = new Filter().dao();
	
	public Set<String> getAttrNames() {
		return this._getTable().getColumnNameSet();
	}
}
