package com.healta.model;

import com.healta.model.base.BaseFollowup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Followup extends BaseFollowup<Followup> {
	public static final Followup dao = new Followup().dao();
}
