package com.healta.model;

import com.healta.model.base.BaseId1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Id1 extends BaseId1<Id1> {
	public static final Id1 dao = new Id1().dao();
}
