package com.healta.model;

import com.healta.model.base.BaseId2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Id2 extends BaseId2<Id2> {
	public static final Id2 dao = new Id2().dao();
}
