package com.healta.model;

import com.healta.model.base.BaseId3;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Id3 extends BaseId3<Id3> {
	public static final Id3 dao = new Id3().dao();
}
