package com.healta.model;

import com.healta.model.base.BaseLabel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Label extends BaseLabel<Label> {
	public static final Label dao = new Label().dao();
}
