package com.healta.model;

import com.healta.model.base.BaseLabelfolder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Labelfolder extends BaseLabelfolder<Labelfolder> {
	public static final Labelfolder dao = new Labelfolder().dao();
}
