package com.healta.model;

import com.healta.model.base.BaseModalityRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ModalityRecord extends BaseModalityRecord<ModalityRecord> {
	public static final ModalityRecord dao = new ModalityRecord().dao();
}
