package com.healta.model;

import com.healta.model.base.BaseModules;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Modules extends BaseModules<Modules> {
	public static final Modules dao = new Modules().dao();
}
