package com.healta.model;

import com.healta.model.base.BaseMwlitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mwlitem extends BaseMwlitem<Mwlitem> {
	public static final Mwlitem dao = new Mwlitem().dao();
	
	public Mwlitem findByAccessionNo(String accession_no){
		return dao.findFirst("SELECT TOP 1 * FROM mwlitem WHERE accession_no = ?", accession_no);
	}
}
