package com.healta.model;

import com.healta.model.base.BaseNoticeRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NoticeRecord extends BaseNoticeRecord<NoticeRecord> {
	public static final NoticeRecord dao = new NoticeRecord().dao();
}
