package com.healta.model;

import com.healta.model.base.BasePasswordPolicy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PasswordPolicy extends BasePasswordPolicy<PasswordPolicy> {
	public static final PasswordPolicy dao = new PasswordPolicy().dao();
}
