package com.healta.model;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Map.Entry;

import org.apache.commons.lang.StringUtils;

import com.healta.model.base.BasePatient;
import com.jfinal.kit.StrKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Patient extends BasePatient<Patient> {
	public static final Patient dao = new Patient().dao();
	
	public Patient getPatientById(String patientid){
		return dao.findFirst("select top 1 * from patient where patientid=?", patientid);
	}
	
	public Patient getPatientByIdAndName(String patientid,String name){
		return dao.findFirst("select top 1 * from patient where patientid=? and patientname=?", patientid,name);
	}
	
	public List<Patient> getPatientByName(String name){
		return dao.find("select *,(select name_zh from syscode where syscode.code=patient.sex and syscode.type='0001') as sexdisplay,"
				+ "(select name_zh from syscode where syscode.code=patient.ageunit and syscode.type='0008') as ageunitdisplay from patient where patientname=?",name);
	}
	
	/*
	 * 返回model的所有属性值字符串。
	 * 请自定义方法不用以get开头
	 * 
	 * */
	public String toStr(){
		String ret="";
		for (Entry<String, Object> entry : this._getAttrsEntrySet()) {
            ret=ret.concat(entry.getKey()).concat(":").concat(entry.getValue()!=null?entry.getValue().toString():"").concat("\r\n");
        }
		return ret;
	}
	
	/*
	 * 返回model的select字符串。
	 * exceptAttrName: 排除一个属性,多个属性中间以','相隔
	 * */
	public String toSelectStr(String excludAttrName){
		String ret="";
		List<String> excludlist=new ArrayList<String>();
		if(StrKit.notBlank(excludAttrName)) {
			excludlist=Arrays.asList(excludAttrName.split(","));
		}
		String tableName=this._getTable().getName();
		for(String attrname:this._getTable().getColumnNameSet()) {
			if(excludlist.contains(attrname))continue;
			ret+=tableName+"."+attrname+",";
		}
		return ret.substring(0, ret.length()-1);
	}
	
	public static void main(String[] arg){
		Patient patient=new Patient();
		patient.setAddress("fds");
		patient.setPatientname("dd");
		System.out.println(patient.toStr());
		System.out.println(patient.toJson());
//		System.out.println(patient.toSelectStr(""));
	}
}
