package com.healta.model;

import com.healta.model.base.BasePatientcallingrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Patientcallingrecord extends BasePatientcallingrecord<Patientcallingrecord> {
	public static final Patientcallingrecord dao = new Patientcallingrecord().dao();
}
