package com.healta.model;

import com.healta.model.base.BasePatientRecycle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PatientRecycle extends BasePatientRecycle<PatientRecycle> {
	public static final PatientRecycle dao = new PatientRecycle().dao();
}
