package com.healta.model;

import com.healta.model.base.BasePhraseNode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PhraseNode extends BasePhraseNode<PhraseNode> {
	public static final PhraseNode dao = new PhraseNode().dao();
}
