package com.healta.model;

import com.healta.model.base.BasePhrase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Phrase extends BasePhrase<Phrase> {
	public static final Phrase dao = new Phrase().dao();
}
