package com.healta.model;

import com.healta.model.base.BasePrinter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Printer extends BasePrinter<Printer> {
	public static final Printer dao = new Printer().dao();
}
