package com.healta.model;

import com.healta.model.base.BasePrinttemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Printtemplate extends BasePrinttemplate<Printtemplate> {
	public static final Printtemplate dao = new Printtemplate().dao();
}
