package com.healta.model;

import com.healta.model.base.BasePurchaseOrderLines;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseOrderLines extends BasePurchaseOrderLines<PurchaseOrderLines> {
	public static final PurchaseOrderLines dao = new PurchaseOrderLines().dao();
}
