package com.healta.model;

import java.util.List;

import com.healta.model.base.BasePurchaseOrder;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PurchaseOrder extends BasePurchaseOrder<PurchaseOrder> {
	public static final PurchaseOrder dao = new PurchaseOrder().dao();

	public List<Record> findOrderStatus(String string) {
		String sql="select t.status  from purchase_order t  group by t.status";
		List<Record> list=Db.find(sql);
		return list;
	}

	public List<Record> getNodes(String status) {
		String sql="select t.id,t.purchase_no  from purchase_order t  where t.status='"+status+"' and deleted=0";
		List<Record> list=Db.find(sql);
		return list;
	}

	public Record findSscPurchase(String id) {
		String sql="select *  from purchase_order t  where t.id='"+id+"'";
		return Db.findFirst(sql);
	}

	public List<Record> findSscPurchaseLines(String id) {
		String sql="select *,pur_qty as order_qty from purchase_order_lines where purchase_id='"+id+"'";
		return Db.find(sql);
	}

	public Record getNewNum() {
		String sql="select count(*) AS num from purchase_order t where   CONVERT(varchar(100),t.cteatetime,23)=CONVERT(varchar(100), GETDATE(), 23);";
		return Db.findFirst(sql);
	}

	public boolean deleteSscPurchase(Integer id) {
		String sql="update purchase_order  set deleted=1 where id='"+id+"'";
		int i=Db.update(sql);
		if(i==1) {
			return true;
		}
		return false;
	}

}
