package com.healta.model;

import com.healta.model.base.BaseRejectopinion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rejectopinion extends BaseRejectopinion<Rejectopinion> {
	public static final Rejectopinion dao = new Rejectopinion().dao();
}
