package com.healta.model;

import com.healta.model.base.BaseReporticd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reporticd extends BaseReporticd<Reporticd> {
	public static final Reporticd dao = new Reporticd().dao();
}
