package com.healta.model;

import com.healta.model.base.BaseReportremark;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reportremark extends BaseReportremark<Reportremark> {
	public static final Reportremark dao = new Reportremark().dao();
}
