package com.healta.model;

import com.healta.model.base.BaseReporttemplatenode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reporttemplatenode extends BaseReporttemplatenode<Reporttemplatenode> {
	public static final Reporttemplatenode dao = new Reporttemplatenode().dao();
}
