package com.healta.model;

import com.healta.model.base.BaseReporttemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reporttemplate extends BaseReporttemplate<Reporttemplate> {
	public static final Reporttemplate dao = new Reporttemplate().dao();
}
