package com.healta.model;

import com.healta.model.base.BaseReport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Report extends BaseReport<Report> {
	public static final Report dao = new Report().dao();
	
	public Report getReportByStudyid(String studyid){
		return dao.findFirst("SELECT * FROM report WHERE studyid=?", studyid);
	}

}
