package com.healta.model;

import com.healta.model.base.BaseReportlabel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reportlabel extends BaseReportlabel<Reportlabel> {
	public static final Reportlabel dao = new Reportlabel().dao();
}
