package com.healta.model;

import com.healta.model.base.BaseReportrace;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reportrace extends BaseReportrace<Reportrace> {
	public static final Reportrace dao = new Reportrace().dao();
}
