package com.healta.model;

import com.healta.model.base.BaseResearchTestgroupForm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchTestgroupForm extends BaseResearchTestgroupForm<ResearchTestgroupForm> {
	public static final ResearchTestgroupForm dao = new ResearchTestgroupForm().dao();
}
