package com.healta.model;

import com.healta.model.base.BaseResearchUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchUserRole extends BaseResearchUserRole<ResearchUserRole> {
	public static final ResearchUserRole dao = new ResearchUserRole().dao();
}
