package com.healta.model;

import com.healta.model.base.BaseResearchResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchResource extends BaseResearchResource<ResearchResource> {
	public static final ResearchResource dao = new ResearchResource().dao();
}
