package com.healta.model;

import com.healta.model.base.BaseResearchRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchRole extends BaseResearchRole<ResearchRole> {
	public static final ResearchRole dao = new ResearchRole().dao();
}
