package com.healta.model;

import com.healta.model.base.BaseResearchRoleAuthority;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchRoleAuthority extends BaseResearchRoleAuthority<ResearchRoleAuthority> {
	public static final ResearchRoleAuthority dao = new ResearchRoleAuthority().dao();
}
