package com.healta.model;

import com.healta.model.base.BaseResearchJoingroupRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchJoingroupRule extends BaseResearchJoingroupRule<ResearchJoingroupRule> {
	public static final ResearchJoingroupRule dao = new ResearchJoingroupRule().dao();
}
