package com.healta.model;

import com.healta.model.base.BaseResearchId1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchId1 extends BaseResearchId1<ResearchId1> {
	public static final ResearchId1 dao = new ResearchId1().dao();
}
