package com.healta.model;

import com.healta.model.base.BaseResearchJoingroupApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchJoingroupApply extends BaseResearchJoingroupApply<ResearchJoingroupApply> {
	public static final ResearchJoingroupApply dao = new ResearchJoingroupApply().dao();
}
