package com.healta.model;

import com.healta.model.base.BaseResearchFormData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchFormData extends BaseResearchFormData<ResearchFormData> {
	public static final ResearchFormData dao = new ResearchFormData().dao();
}
