package com.healta.model;

import com.healta.model.base.BaseResearchJoingroupApplyItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchJoingroupApplyItems extends BaseResearchJoingroupApplyItems<ResearchJoingroupApplyItems> {
	public static final ResearchJoingroupApplyItems dao = new ResearchJoingroupApplyItems().dao();
}
