package com.healta.model;

import com.healta.model.base.BaseResearchTestGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchTestGroup extends BaseResearchTestGroup<ResearchTestGroup> {
	public static final ResearchTestGroup dao = new ResearchTestGroup().dao();
}
