package com.healta.model;

import com.healta.model.base.BaseResearchProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchProject extends BaseResearchProject<ResearchProject> {
	public static final ResearchProject dao = new ResearchProject().dao();
}
