package com.healta.model;

import com.healta.model.base.BaseResearchAuthority;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchAuthority extends BaseResearchAuthority<ResearchAuthority> {
	public static final ResearchAuthority dao = new ResearchAuthority().dao();
}
