package com.healta.model;

import com.healta.model.base.BaseResearchAuthorityResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchAuthorityResource extends BaseResearchAuthorityResource<ResearchAuthorityResource> {
	public static final ResearchAuthorityResource dao = new ResearchAuthorityResource().dao();
}
