package com.healta.model;

import com.healta.model.base.BaseResearchJoingroupRuleItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ResearchJoingroupRuleItem extends BaseResearchJoingroupRuleItem<ResearchJoingroupRuleItem> {
	public static final ResearchJoingroupRuleItem dao = new ResearchJoingroupRuleItem().dao();
}
