package com.healta.model;

import java.util.List;

import com.healta.model.base.BaseResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resource extends BaseResource<Resource> {
	public static final Resource dao = new Resource().dao();
	
	
	public List<Resource> getWithAuthAll() {
		return Resource.dao.find("select r.*, a.name as authorityName from resource r "
				+ "left join authority_resource ar on r.rid = ar.resource_id "
				+ "left join authority a on a.id =ar.authority_id");
	}
}
