package com.healta.model;

import com.healta.model.base.BaseRetrialviewlist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Retrialviewlist extends BaseRetrialviewlist<Retrialviewlist> {
	public static final Retrialviewlist dao = new Retrialviewlist().dao();
}
