package com.healta.model;

import com.healta.constant.CacheName;
import com.healta.model.base.BaseRisTrigger;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RisTrigger extends BaseRisTrigger<RisTrigger> {
	public static final RisTrigger dao = new RisTrigger().dao();
	
	
	public Record getRisTriggers() {
		Record ret=new Record();
		dao.findByCache(CacheName.DICCACHE, "ris_triggers", "select * from ris_trigger").stream().forEach(x->{
			ret.set(x.getName(), x.getOnOff());
		});
		return ret;
	}
}
