package com.healta.model;

import com.healta.model.base.BaseRoleAuthority;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleAuthority extends BaseRoleAuthority<RoleAuthority> {
	public static final RoleAuthority dao = new RoleAuthority().dao();
}
