package com.healta.model;

import com.healta.model.base.BaseRoleModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleModule extends BaseRoleModule<RoleModule> {
	public static final RoleModule dao = new RoleModule().dao();
}
