package com.healta.model;

import com.healta.model.base.BaseSrcomponentoption;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Srcomponentoption extends BaseSrcomponentoption<Srcomponentoption> {
	public static final Srcomponentoption dao = new Srcomponentoption().dao();
}
