package com.healta.model;

import com.healta.model.base.BaseSscSaleOrderLines;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SscSaleOrderLines extends BaseSscSaleOrderLines<SscSaleOrderLines> {
	public static final SscSaleOrderLines dao = new SscSaleOrderLines().dao();
}
