package com.healta.model;

import com.healta.model.base.BaseStatisticalclassify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Statisticalclassify extends BaseStatisticalclassify<Statisticalclassify> {
	public static final Statisticalclassify dao = new Statisticalclassify().dao();
}
