package com.healta.model;

import com.healta.model.base.BaseStatisticalcustomconditions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Statisticalcustomconditions extends BaseStatisticalcustomconditions<Statisticalcustomconditions> {
	public static final Statisticalcustomconditions dao = new Statisticalcustomconditions().dao();
}
