package com.healta.model;

import com.healta.model.base.BaseStatisticalreport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Statisticalreport extends BaseStatisticalreport<Statisticalreport> {
	public static final Statisticalreport dao = new Statisticalreport().dao();
}
