package com.healta.model;

import com.healta.model.base.BaseStatusColor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatusColor extends BaseStatusColor<StatusColor> {
	public static final StatusColor dao = new StatusColor().dao();
}
