package com.healta.model;

import java.util.List;
import java.util.Map;

import com.healta.model.base.BaseStock;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Stock extends BaseStock<Stock> {
	public static final Stock dao = new Stock().dao();
	
	/**
	 * 根据商品ID,商品批号,有效日期,失效日期查询库存记录
	 * @return
	 */
	public List<Stock> findStock(Map<String,String> map){
		String sql="select * from stock  t where t.goods_id='"+map.get("goods_id")+"' and t.com_lot='"+map.get("com_lot")+"' and t.efficiency_date='"+map.get("efficiency_date")+"' and t.expire_date='"+map.get("expire_date")+"'";
		return dao.find(sql);
	}

	public List<Record> findGoodsStock(Map<String,String> map) {
		StringBuffer sb =new StringBuffer();
		sb.append(" select goods.goods_id,goods.goods_name,goods.com_lot,goods.efficiency_date,goods.expire_date,goods.calibration_dose,goods.capacity,sum(goods.onavailable) as onavailable from (");
		sb.append(" SELECT t.goods_id,t.goods_name,t.com_lot,t.efficiency_date,t.expire_date,cg.calibration_dose,cg.capacity,t.onavailable");
		sb.append(" FROM ");
		sb.append(" stock t");
		sb.append("  inner join com_goods cg   on t.goods_id=cg.id  where  t.onavailable>0");
		if(StrKit.notNull(map.get("goods_id"))&&StrKit.notBlank(map.get("goods_id"))) {
			sb.append(" and t.goods_id='"+map.get("goods_id")+"'");
		}
		if(StrKit.notNull(map.get("goods_name"))&&StrKit.notBlank(map.get("goods_name"))) {
			sb.append(" and t.goods_name='"+map.get("goods_name")+"'");
		}
		sb.append("  ) as goods");
		sb.append(" group by ");
		sb.append(" goods.goods_id,goods.goods_name,goods.com_lot,goods.efficiency_date,goods.expire_date,goods.calibration_dose,goods.capacity");
		return Db.find(sb.toString());
	}
}
