package com.healta.model;

import com.healta.model.base.BaseStructreport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Structreport extends BaseStructreport<Structreport> {
	public static final Structreport dao = new Structreport().dao();
}
