package com.healta.model;

import com.healta.model.base.BaseStudyitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Studyitem extends BaseStudyitem<Studyitem> {
	public static final Studyitem dao = new Studyitem().dao();
}
