package com.healta.model;

import com.healta.model.base.BaseStudyprocess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Studyprocess extends BaseStudyprocess<Studyprocess> {
	public static final Studyprocess dao = new Studyprocess().dao();
}
