package com.healta.model;

import com.healta.model.base.BaseStudyorderNumber;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudyorderNumber extends BaseStudyorderNumber<StudyorderNumber> {
	public static final StudyorderNumber dao = new StudyorderNumber().dao();
}
