package com.healta.model;

import com.healta.model.base.BaseStudyImage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudyImage extends BaseStudyImage<StudyImage> {
	public static final StudyImage dao = new StudyImage().dao();
	
	public StudyImage findByOrderid(Integer orderid) {
		return dao.findFirst("select top 1 * from study_image where orderid=?", orderid);
	}
}
