package com.healta.model;

import com.healta.model.base.BaseStudyMaterialDefault;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudyMaterialDefault extends BaseStudyMaterialDefault<StudyMaterialDefault> {
	public static final StudyMaterialDefault dao = new StudyMaterialDefault().dao();
}
