package com.healta.model;

import com.healta.model.base.BaseStudyAcquisitionModeDefault;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudyAcquisitionModeDefault extends BaseStudyAcquisitionModeDefault<StudyAcquisitionModeDefault> {
	public static final StudyAcquisitionModeDefault dao = new StudyAcquisitionModeDefault().dao();
}
