package com.healta.model;

import com.healta.model.base.BaseStudyMethodTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StudyMethodTemplate extends BaseStudyMethodTemplate<StudyMethodTemplate> {
	public static final StudyMethodTemplate dao = new StudyMethodTemplate().dao();
}
