package com.healta.model;

import com.healta.model.base.BaseSynctime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Synctime extends BaseSynctime<Synctime> {
	public static final Synctime dao = new Synctime().dao();
	
	public Synctime getSynctime(){
		return dao.findFirst("select * from synctime");
	}
}
