package com.healta.model;

import com.healta.model.base.BaseSyngoviaimage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Syngoviaimage extends BaseSyngoviaimage<Syngoviaimage> {
	public static final Syngoviaimage dao = new Syngoviaimage().dao();
	
	
	public Syngoviaimage getImageByImageid(String imageid,String studyid){
		return dao.findFirst("select * from syngoviaimage where imageid=? and studyid=? and delflag=0", imageid,studyid);
	}
	
	public Syngoviaimage getImageByImageUid(String imageid,String studyinsuid){
		return dao.findFirst("select * from syngoviaimage where imageid=? and studyinsuid=? and delflag=0", imageid,studyinsuid);
	}
}
