package com.healta.model;

import com.healta.model.base.BaseSyngoviasrdata;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Syngoviasrdata extends BaseSyngoviasrdata<Syngoviasrdata> {
	public static final Syngoviasrdata dao = new Syngoviasrdata().dao();
}
