package com.healta.model;

import com.healta.model.base.BaseSyngoviafindingfile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Syngoviafindingfile extends BaseSyngoviafindingfile<Syngoviafindingfile> {
	public static final Syngoviafindingfile dao = new Syngoviafindingfile().dao();
	
	public static int getCountByFindingname(String studyinsuid,String findingname){
		int ret=0;
		Syngoviafindingfile f=dao.findFirst("select count(id) as count from syngoviafindingfile where studyinsuid=? and findingname=?",studyinsuid,findingname);
		
		if(f!=null){
			ret=Integer.valueOf(f.get("count")+"");
		}
		return ret;
	}
}
