package com.healta.model;

import com.healta.model.base.BaseSyscode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Syscode extends BaseSyscode<Syscode> {
	public static final Syscode dao = new Syscode().dao();
}
