package com.healta.model;

import com.healta.model.base.BaseTaskRolePersonnel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskRolePersonnel extends BaseTaskRolePersonnel<TaskRolePersonnel> {
	public static final TaskRolePersonnel dao = new TaskRolePersonnel().dao();
}
