package com.healta.model;

import com.healta.model.base.BaseUnmatchstudy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Unmatchstudy extends BaseUnmatchstudy<Unmatchstudy> {
	public static final Unmatchstudy dao = new Unmatchstudy().dao();
}
