package com.healta.model;

import com.healta.model.base.BaseUrgent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Urgent extends BaseUrgent<Urgent> {
	public static final Urgent dao = new Urgent().dao();
}
