package com.healta.model;

import com.healta.model.base.BaseUserProfiles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserProfiles extends BaseUserProfiles<UserProfiles> {
	public static final UserProfiles dao = new UserProfiles().dao();
}
