package com.healta.model;

import com.healta.model.base.BaseUserAuditLogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAuditLogs extends BaseUserAuditLogs<UserAuditLogs> {
	public static final UserAuditLogs dao = new UserAuditLogs().dao();
}
