package com.healta.model;

import com.healta.model.base.BaseUserShortcutConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserShortcutConfig extends BaseUserShortcutConfig<UserShortcutConfig> {
	public static final UserShortcutConfig dao = new UserShortcutConfig().dao();
}
