package com.healta.model;

import com.healta.model.base.BaseUserDac;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserDac extends BaseUserDac<UserDac> {
	public static final UserDac dao = new UserDac().dao();
}
