package com.healta.model;

import com.healta.model.base.BaseXslttemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Xslttemplate extends BaseXslttemplate<Xslttemplate> {
	public static final Xslttemplate dao = new Xslttemplate().dao();
	
	public Xslttemplate getXsltByName(String name,String reportname,String version){
		return dao.findFirst("select * from xslttemplate where name=? and belongreport like '%"+reportname+"%' and viaversion=?",name,version);
	}
	
	public Xslttemplate getXsltByName(String name,String version){
		return dao.findFirst("select * from xslttemplate where name=? and viaversion=?",name,version);
	}
}
